Makefile

Temporarily disable LASP tests due to problems with LASP test accounts.

Temporarily disable LASP tests

---

src/newrelic/infinite_tracing/grpc_sender.go
src/newrelic/infinite_tracing/trace_observer.go
src/newrelic/infinite_tracing/trace_observer_test.go

This enables the daemon to attempt a reconnect on 8T cell shifts.
How it works:
1. The `spanBatchSender` interface is extended by a `clone` method. This method returns a clone of the sender (duplicating the underlying configuration). The clone establishes its own TCP connection (which also includes resolving the host name).
2. There's an additional `statusReconnect` constant, signifying that a TCP reconnect is needed.
3. The `FailedPrecondition` gRPC return code is translated into a `statusReconnect` status.
4. In the main worker loop, if a `statusReconnect` status is received, the store sender is shut down, cloned, and replaced with its clone.

PHP-2672: Reconnect on FailedPrecondition

---

agent/php_newrelic.c

Previously, the value of ReflectionParameter->getName() were of the form
`'"parameter"'`, not `'parameter'`
Aside, out of scope: PHP 8 introduces named arguments. There's snake_case elsewhere - maybe function_name should be used instead of functionname (would also need to update docs)

Fix C macros for arginfo parameter names

---

.github/stale.yml

This PR configures stalebot to ignore issues that we have yet to triage or tickets that we have accepted into our backlog.

stalebot: Add 'backlog' and 'triage' to exempt labels

---

axiom/Makefile

When building the agent, you currently have to run the build in parallel with something like `-j 4`. This PR fixes that.
`v1.pb-c.h` is generated when we compile `v1.pb-c.h`. The problem is, it is last in the list. `nr_span_encoding.c` needs it to be present for it to be able to build. The reason the `-j` workaround works is that it launches enough threads to compile `v1.pb-c.c` before `nr_span_encoding.c`.
By forcing `v1.pb-c.c` to be compiled first, we ensure that, regardless of which files need it to be present, it will be guaranteed to be there.
There are alternative fixes we could explore such as manually calling `protoc-c` earlier in the build process, tweaking the compile step for all `c` files, or adding a new dependency for the files that need the header file to be there, but …

Fix parallel build problem: Move protobuf header generation

---

agent/php_curl.c
agent/php_curl_md.c
agent/php_internal_instrument.c

Refactors all curl resource checks to account for the fact that in PHP 8, it is an object.
The necessary changes are nicely[ summarized here](https://php.watch/versions/8.0/resource-CurlHandle).  As you can see, API compatibility was very well maintained by the upstream code in PHP, but also somewhat surprisingly, in C as well.
Unit tests (with valgrind) pass with no issues, and small manual curl test program is correctly instrumented.
Fixes #42
Fixes #51

PHP 8 curl Object Fixes

---

.github/stale.yml

This adds the `epic` label to the exempt labels used by stalebot.

Add epic to stalebot's exemptLabels

---

agent/fw_magento2.c

`prepareOperationInput` was Introduced in Magento 2.3.2 to convert arguments received from SOAP server to arguments to pass to a service. Fixes issue #55 .
It takes the following arguments:
* string $serviceClass
* array $methodMetadata
* array $arguments
Prior to the fix, a SOAP API call would be displayed as:
`WebTransaction/Action/FrontController/Magento\Webapi\Controller\Interceptor`
After the fix, 
It shows up in the UI as `/Webapi/Soap/Magento\Integration\Api\AdminTokenServiceInterface/createAdminAccessToken`
Tested with the following `php` file:
```
<?php
$request = new SoapClient("http://magento2.docker/soap/?wsdl&services=integrationAdminTokenServiceV1", array("soap_version" => SOAP_1_2));
$token = $request->integrationAdminTokenServiceV1CreateAdminAccessToken(array("username"=>"P …
```

Instrument Magento2 `prepareOperationInput`.

---

agent/config.m4

The `-ldl` flag added in https://github.com/newrelic/newrelic-php-agent/pull/73/commits/37901aa669dcdf408154e07bb0abdabaeb6f0f6b was the culprit of the build errors on FreeBSD.  Interestingly, the flag itself is not needed for the `agent`'s `autoconf` `axiom` lib check to pass on FreeBSD.  To get around this in an easily modifiable way, I've added a case statement that when on FreeBSD, omits the the `-ldl` arg, but defaults to including it.  If we encounter any issues with this in other scenarios, adding them to the FreeBSD block is all we need to get around the error.
Tested manually by logging in to Jenkins FreeBSD worker, pulling in this change and internal repo, and running both `build.sh` and `build-pull-request.sh` successfully.

Remove -ldl in agent autoconf axiom check on BSD

---

agent/newrelic-install.sh

This PR adds the needed references to PHP 8.0 and API version 20200930 needed to be able to install the PHP8 version of the agent. It also adds the API version of PHP 7.4 to one of the sets of file checks (see line 315). I believe its absence was an oversight.
I tested this by locally modifying `make/release.mk` to add the needed targets to build the PHP 8.0 version of the agent. I manually combined those results with the contents from a previous release so I had all versions of the agent in the release directory. This was enough to get all the file existence checks in the install script to pass which allowed me to test the installation logic.
Note: Once this PR is merged, installs will fail unless the PHP 8.0 version of the agent is in the agent's package. We may want to hold off on …

Update newrelic-install.sh to support PHP 8.0

---

.github/docker/linux/pr_build.sh
.github/docker/linux/release_build.sh
.github/docker/linux/x64/Dockerfile
.github/docker/linux/x86/Dockerfile
.github/workflows/agent-build.yml
make/release.mk

1) Workflows to build release and PR for PHP 8.0.
2) Dockerfiles
3) Build scripts.
Issues:
1) `Integration tests` are currently disabled for PHP 8.0 builds while we work on upgrading those tests.
2) `valgrind` for PHP8.0 on 32bit OS turned up a memory issue.  `valgrind` on 64bit had compilation issue.`valgrind` check is disabled for PHP 8 on both 32-bit/64-bit dues to issues. Maybe it can be looked at as part of #62.
3) Because GHA does [not currently support](https://github.community/t/feature-request-build-args-support-in-docker-container-actions/16846) passing `—build-args` to a Dockerfile in an action, and in order to reduce the proliferation of Dockerfiles (phpver X OS X arch X zts/nozts), currently we build/run a Dockerfile in separate steps.  This can be revisited if/when GHA …

GHA workflow with associated Dockerfiles and build scripts.

---

.github/docker/linux/pr_build.sh
.github/docker/linux/x64/Dockerfile
.github/workflows/agent-build.yml

* Addressed the 64-bit valgrind issue.  The PHP 8.0 build now does unit tests with valgrind.
* Changed the workflow to show 7.x builds on x64.
Issues:
1) On GHA unit tests skip for 7.2 and below because SAPI embed was not compiled into that PHP image.
2) Integration tests:
We can disable lasp on the GHA runs, but it still asks for private keys (like license key).
3) 5.5 and 5.6 on x64
Axiom builds, but agent build can’t find axiom.
4) Now that valgrind runs on 64-bit, it's surfaced a possible memory issue that needs to be investigated.

PHP: 64-bit valgrind now builds correctly.

---

agent/php_file_get_contents.c
tests/include/tracing_endpoint.php
tests/integration/external/file_get_contents/test_dt_context_provided.php

This PR prevents a build up of Distributed Tracing headers from being added to a request when using `file_get_contents` and reusing the stream context parameter.
It does this by:
* Modifying the test trace endpoint to detect if there is more than one value for a distributed tracing header
* Adding a scenario that reuses the stream context when calling `file_get_contents`, this triggers the modified detection logic in the trace endpoint
* Updating `nr_php_file_get_contents_add_headers_internal` to detect if one of the DT headers are present in both the existing headers string and the headers that are about to be added. This change assumes that all of the DT headers are added as a group and that detecting one of them is sufficient.
The flow goes roughly like this:
* …

Prevent build up of duplicate Distributed Tracing headers

---

.github/docker/linux/pr_build.sh
agent/tests/valgrind-suppressions
axiom/tests/valgrind-suppressions

* Added suppressions for valgrind message generated on the 32bit compiler.
Valgrind had been generating the following message:
```
tests/test_globals.valgrind.log
==40137== Memcheck, a memory error detector
==40137== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==40137== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==40137== Command: ./tests/test_globals
==40137== Parent PID: 40071
==40137== 
==40137== Invalid read of size 4
==40137==    at 0x4952692: check_free (dlerror.c:188)
==40137==    by 0x4952BD8: free_key_mem (dlerror.c:221)
==40137==    by 0x4952BD8: __dlerror_main_freeres (dlerror.c:239)
==40137==    by 0x61FA667: __libc_freeres (in /lib/i386-linux-gnu/libc-2.28.so)
==40137==    by 0x482D1DE: _vgnU_freeres (vg_preloaded.c:77)
==40137== …
```

PHP 8: Added suppression for 32bit compiler

---

agent/php_error.c
tests/integration/errors/test_E_NOTICE.php
tests/integration/errors/test_E_PARSE.zend.php8.php
tests/integration/errors/test_ignore_E_WARNING.php

This is part of the fixes for #107. The changes unique to this PR fix our error handling related integration tests. This required both changes to the tests and the agent.
In `php_error.c`, we need to strip off `E_DONT_BAIL` from the error type. `E_DONT_BAIL` is a new error value [added in PHP 8](https://github.com/php/php-src/commit/db233501ff9d56765ef4a870b777a643c2136711) that is used to indicate to the runtime that a clean exit should be performed. To avoid having to sprinkle this modification of `type` in several places, this is done just once in `nr_php_error_cb` prior to any of the other related functions being called.
In PHP 8.0+, the format string for an exception is [expanded](https://github.com/php/php-src/blob/PHP-8.0/Zend/zend_exceptions.c#L905-L914) before it gets to us. In …

Fix error handling related integration tests

---

tests/integration/errors/test_E_NOTICE.php8.php
tests/integration/errors/test_ignore_E_WARNING.php8.php

#124 changed a couple of error handling related tests, but the functions chosen do not exist on all versions of PHP we test against or display a different error message.
Rather than taking the time to either find an alternative that exists across all PHP versions or tweaking the expected error message so it matches across all PHP versions, this PR restores the old versions of those tests for older versions of PHP and adds new versions for PHP 8.0+.

Fix NOTICE and WARNING tests on other PHP versions

---

agent/lib_zend_http.c

Defect surfaced during test cases runs.
After determining it wasn't a problem with the test case, put in the fix and retested with the failing test case which now passes.
This is for the zend_http library (not the zend framework) which was failing a zend 1.x zend_http library test.

Fix to zend_http_client which surfaced during multiverse test.

---

agent/php_error.c
agent/php_execute.c

This PR fixes a couple of memory leaks introduced in v9.12 of the agent.
* A string that wasn't freed in `nr_php_error_record_exception_segment`.
* The memory pointed to by `segment->error` when an exception occurs in a stacked segment that is not converted to a heap segment.
The fix for the latter involves converting the stacked segment to a heap allocated segment prior to deallocation if `segment->error` is set. The pre-existing code does the same thing if `segment->attributes` is set.

Fix memory leak that occurs when exceptions occur in stacked segments

---

agent/newrelic-install.sh
make/release.mk

This PR:
* updates the `release` target to build for PHP 8.0, but only on 64-bit targets.
* modifies the `newrelic-install.sh` script to not look for PHP 8.0 builds when installing on either 32-bit or 64-bit targets.

PHP 8.0 agent build and install changes

---

agent/fw_lumen.c

This fixes transaction naming for Laravel Lumen and adds a bit of cleanup.

Fix Laravel Lumen txn naming

---

agent/php_call.c
agent/php_pdo.c
tests/integration/pdo/test_prepared_stmt_params.php

This PR fixes issue #143.
In the PHP 8 [upgrading internals](https://github.com/php/php-src/blob/PHP-8.0.0/UPGRADING.INTERNALS) document, there is this note:
>   The zend_fcall_info no_separation flag has been removed, and separation is
never allowed. If you wish to pass (or allow passing) arguments by
reference, explicitly create those arguments as references using
ZEND_MAKE_REF. This removal also affects call_user_function_ex(), which
should be replaced by call_user_function().
Here are some details about what that means in practice and how it compares to previous PHP releases.
PHP 8.0 emits a warning [when a reference is needed and wasn't provided](https://github.com/php/php-src/blob/PHP-8.0.3/Zend/zend_execute_API.c#L770-L776). The runtime still [creates a …

Pass parameters by reference when calling bindParam

---

agent/newrelic-install.sh

I'm currently testing Php8 support provided by the last version `9.17.1.301`.
While migrating my installation script, I noticed that the file `/etc/php/8.0/fpm/conf.d/newrelic.ini` doesn't exist anymore by default after installation process on Ubuntu (but `/etc/php/8.0/cli/conf.d/newrelic.ini` still exists!).
After searching in the installation script, I guess that possible config paths to explore have not been updated. Here a patch proposal, but I didn't test nor search extensively if there is something elsewhere, I just wanted to understand *why* it was different 😅

fix(php8): default newrelic.ini file in fpm/conf.d

---

agent/php_curl.c

This PR fixes a memory leak in our curl-mutli instrumentation.
The agent [creates metadata](https://github.com/newrelic/newrelic-php-agent/blob/490d52afc560f9d8cbcda88571b6a564ea6c139e/agent/php_curl_md.c#L344-L356) for each curl multi handle. The metadata includes, among other things, [a vector](https://github.com/newrelic/newrelic-php-agent/blob/490d52afc560f9d8cbcda88571b6a564ea6c139e/agent/php_curl_md.h#L22-L23) of curl handle `zval`s. When a new curl handle is added to a multi handle, it is [added to this vector](https://github.com/newrelic/newrelic-php-agent/blob/490d52afc560f9d8cbcda88571b6a564ea6c139e/agent/php_curl_md.c#L358-L368). When a handle is manually removed from the multi handle, it is [removed from the vector](https://github.com/newrelic/newrelic-php-agent/blob/490d52afc5 …

Fix curl multi memory leak

---

Makefile
docker-compose.yaml
docs/dev_environment.md
files/Dockerfile
files/Dockerfile.redis
files/redis.conf
files/set_path.sh

This is a prototype of a dockerized development environment that would allow contributors to both develop and test (using unit tests AND integration tests) without having to set up a specific environment on their own system.  Integration tests send actual data to the New Relic backend and therefore requires a license key (Sign up at https://newrelic.com/signup for a free account.).
Currently docker-compose spins up `mysql` and `redis` databases in separate containers.
Two environment variables to note:
`NEWRELIC_LICENSE_KEY` is required to run the integration tests and should be set to your NR license key.
If your collector isn’t the default (collector.newrelic.com), set the `NEWRELIC_COLLECTOR_HOST` to the appropriate value.
PHP_VER can also be set, but hasn’t been tested beyond `8.0`. …

Initial dockerized dev environment prototype.

---

agent/fw_drupal.c
agent/fw_drupal_common.c
agent/fw_drupal_common.h
agent/tests/test_fw_drupal.c

This PR removes the code that attempts to create a `NegativeModuleLength` Supportability metric. The intention behind this metric was to record how often a certain edge case was encountered. Unfortunately, it appears to cause a segfault on at least some systems. The simplest approach here is to just remove the metric as it is currently causing more harm than good.

Remove Drupal NegativeModuleLength Supportability metric

---

axiom/nr_distributed_trace.c
axiom/nr_distributed_trace.h
axiom/nr_segment.c
axiom/nr_txn.c
axiom/tests/test_distributed_trace.c
axiom/tests/test_txn.c

**Context:** I'm facing a strange issue in my NewRelic data, all `parent.transportDuration` values are `0` for transactions between 2 Php applications instrumented by NewRelic. I opened a ticket and they suggest that servers are not synchronized (but I know they are 😉 ). So I dig into the code…
The [`nr_time_duration`](https://github.com/newrelic/newrelic-php-agent/blob/6498785b65c7bf2247a2b268e493d26d5264d83d/axiom/util_time.h#L69-L72) function compute the time elapsed between a `start` timestamp and a `stop` timestamp. If `start > stop`, it returns `0`.
The [`nr_distributed_trace_inbound_get_timestamp_delta` function](https://github.com/newrelic/newrelic-php-agent/blob/6498785b65c7bf2247a2b268e493d26d5264d83d/axiom/nr_distributed_trace.c#L374-L382) intends to return the _transport …

Distributed tracing: time inversion for duration calculation

---

agent/fw_laravel.c

Route::getName() returns a random generated string (generated::*) if a route isn't named [(Named Routes)](https://laravel.com/docs/8.x/routing#named-routes) and routes are cached via `php artisan route:cache` since laravel 7.x.
This causes the problem mentioned in #86. To fix the problem, I added a check if the returned string begins with `generated::`, to skip it and use `Route::getAction()` instead.

Fix laravel transaction naming (issue #86) - Don't use getName() if it's a auto generated route name

---

.github/workflows/release-build.yml

Only the PHP 8.0-zts should remain here so we don't overwrite the PHP 8.0 builds pulled in from Jenkins.

Update PHP 8.0 ZTS build

---

.github/docker/linux/x64/Dockerfile
.github/docker/linux/x86/Dockerfile

CI wasn't running due to a dockerfile build issue.  Modified the dockerfile, but longterm solution should be to store build images.

Update to the CI.  

---

agent/php_curl_md.c
agent/php_zval.h

This PR addresses an issue that was left unnoticed from the transition to PHP 8.0. There was still an instance of using the curl handle as a resource instead of an object. This issue was found when exploring the upgrade to PHP 8.1.

Curl valgrind issue

---

.gitignore
agent/php_api_datastore.c
agent/php_error.c
agent/php_explain_pdo_mysql.c
agent/php_hooks.h
agent/php_includes.h
agent/php_newrelic.h
agent/tests/tlib_php.c

Great job Michael, the prototype seems to be all in order to support PHP 8.1 (with the exception of the valgrind issue that Zach's PR is addressing).  This looks ready to merge. 
Addresses Issue https://github.com/newrelic/newrelic-php-agent/issues/290

PHP 8.1: Agent changes to support PHP 8.1

---

agent/fw_symfony4.c
agent/php_execute.c

HI,
I try to introduce Symfony 5 auto-detect. I prepare this code, but totally I don't have an idea how to check locally if it's working properly, because agent built in dev-shell requires `libpcre.so.3` that isn't available on alpine that I use for docker container.
Also, dev-env don't work on latest dev branch, I remove `python-yaml` library from dockerfile as was done on GH pipelines - https://github.com/newrelic/newrelic-php-agent/commit/2d2e5f374ac08680f7242fa7a9b7b6bdefd5aa0f
This PR fix https://github.com/newrelic/newrelic-php-agent/issues/113

Add Symfony 5 support

---

tests/lasp/suite-least-secure/test_slow_sql_on.php
tests/lasp/suite-least-secure/test_slow_sql_on.php81.php
tests/lasp/suite-random-2/test_slow_sql_on.php81.php

PHP 8.1 changed the behavior of the PDO MySQL extension:
```
PDO MySQL:
Integers and floats in result sets will now be returned using native PHP
types instead of strings when using emulated prepared statements. This
matches the behavior of native prepared statements. You can restore the
previous behavior by enabling the PDO::ATTR_STRINGIFY_FETCHES option.
```
This has impacted some of the LASP "slow sql" test cases which expect a string return value but now on PHP 8.1 it is a numeric value instead.
The fix we adopted in the integration tests for this was to split the test into a "pre-8.1" test and an "8.1 and beyond" test which are guarded by the appropriate code in the SKIPIF.

Fix LASP test cases affected by PHP 8.1 PDO changes

---

agent/php_minit.c
agent/php_newrelic.h
agent/scripts/init.darwin
agent/scripts/init.debian
agent/scripts/init.freebsd
agent/scripts/init.generic
agent/scripts/init.rhel
agent/scripts/init.solaris
axiom/nr_agent.c
axiom/nr_agent.h

Use current location of New Relic for PHP Docs website in init scripts as well as in agent code error messages.

Update URL of New Relic for PHP Docs website used in error messages

---

Makefile
agent/newrelic-install.sh
make/release.mk

Changes:
- agent/newrelic-install.sh:
- Remove references to 5.3 and 5.4 and add 8.1 as required.
- Rework some logic which assumed the only possible 8.x release was 8.0 to work now we have 8.0 and 8.1.
- make/release.mk
- Add guards so 8.1 is only built on 64 bit systems.
- Remove building for 5.3 and 5.4.
Makefile
- Remove 5.3 and 5.4 from lists for version to run for integration and LASP tests.

Updates to support building PHP 8.1 and installer script

---

.github/workflows/agent-build.yml

The agent does not support 32 bit environments running PHP 8.x so we can disable these test builds.
This is the corrected version of PR #335 which was improperly setup targeting 'main' instead of the 'dev' branch.

Disable 32bit builds for PHP 8.x in GitHub workflow

---

agent/newrelic-install.sh

Adds some checking so if the installer is run on an unsupported arch then the installer exits.
On ARM64 ("aarch64" on Linux) a link to the instructions for installing from source is given.

feat(install): Only allow installer to run on supported arches and OSes

---

agent/fw_laravel.c
agent/php_execute.c
agent/php_globals.h
agent/php_txn.c
agent/php_vm.c

* Updated Laravel detection
* Updated preload behavior
* Updated types of zend resource
This was a hard one to debug and analyze due to a few other issues going on.
Summary of details:
One caveat regarding our solution.  While there was an error on our side, there does seem to be some instability with laravel and another process which is not related to NR as the following events were observed with NR disabled.  If the underlying zend memory structures have been corrupted, the agent will be unable to function correctly.  Some of the "unknown" issues were because we queried zend for a class and the underlying structures reported it did not exist.  Once it has been corrupted, for proper naming, the opache needs to be reset.
Again, we've observed this issue with the NR agent disabled.  If …

PHP: Laravel 8+ updates

---

agent/php_nrini.c
agent/scripts/newrelic.cfg.template
agent/scripts/newrelic.ini.template
axiom/nr_daemon_spawn.c
axiom/nr_utilization.h
axiom/tests/reference/test_daemon.cmp
src/daemon/main.go
src/integration_runner/main.go
src/newrelic/collector_integration_test.go
src/newrelic/utilization/addresses.go
src/newrelic/utilization/fqdn.go
src/newrelic/utilization/kubernetes.go
src/newrelic/utilization/provider.go
src/newrelic/utilization/utilization_hash.go
src/newrelic/utilization/utilization_hash_test.go

This PR bumps the daemon up to reporting utilization metadata spec Level 5 which specified the inclusion of the full hostname, host ip address(es), and the Kubernetes service host (if available).  It adds a new daemon config option for "utilization.detect_kubernetes" which defaults to ON.
Much of this work is based on the Go agent (v3) commit to add [Utilization v5](https://github.com/newrelic/go-agent/commit/52464a9e9993b9dad4f904f46102debb5ea9bfc2).
This PR addresses issues #414, #415 and #416.

feat(daemon): Implement Utilization Metadata Spec V5

---

agent/php_vm.c

Unconditional verbosedebug in nr_php_handle_cufa_fcall causes excessive
logging which impacts agent's performance when log level is set to
verbosedebug. It can additionally fill up disk space very quickly.

fix(agent): Remove verbose debug log

---

files/Dockerfile

The existing Dockerfile for creating the agent image for the dockerized agents and services dev env had the composer installer checksum hard codes.  Recently the installer was updated so the docker compose would fail when the checksum didn't match.  This update changes how the composer installation is handles to match the best practice defined [here](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) which involves downloaded the expected checksum as well as the installer payload and comparing.

fix(agent): Rework Dockerfile to improve composer installation

---

src/newrelic/app.go
src/newrelic/app_test.go
src/newrelic/collector/client.go
src/newrelic/collector/client_test.go
src/newrelic/collector/collector_test.go
src/newrelic/limits/limits.go
src/newrelic/processor.go

This PR implements following Agent's specification:
Agents MUST default to sending no more than 1000000 bytes in any payload
sent to New Relic for any method. The connect response contains the
max_payload_size_in_bytes field which MUST override the default value.
Immediately prior to transmitting a payload to New Relic (after
compression, prior to transmission), the size of the payload in bytes
should be compared against max_payload_size_in_bytes. If the payload
size is larger than max_payload_size_in_bytes, the agent should
immediately discard that payload. A payload larger than
max_payload_size_in_bytes MUST NOT be transmitted.
Following tests have been added to cover changed code:
1. Test if default payload limit is preserved if collector doesn't provide any value.
2. Test if default …

feat(daemon): Implement New Relic payload size limit

---

agent/php_minit.c
agent/php_txn.c
axiom/nr_segment.c

This PR improves handling TT, 8T and DT configuration dependencies. In particular:
- If 8T is enabled and DT is disabled then this PR will:
+ Output a warning that 8T will be disabled because DT is disabled.
+ Sets the trace observer host to "" if DT is disabled.
+ If for some reason the previous mitigation failed then it will batch together the previous warning message which occurred each time the creation of a span was attempted which created significant log file output.  Now the message will appear at most once every 60 seconds with a count of the number of times it occurred in the past 60 seconds.
- If DT is enabled and the transaction tracer is disabled it will also batch together the error message which occurs each time the creation of a transaction is created and outputs a summary …

fix(agent): Improve handling TT, 8T and DT configuration dependencies

---

axiom/nr_txn.c
axiom/tests/test_txn.c

Agent will honor server side configuration and will not collect span 
events if this feature is disabled in the configuration received from 
the server. Server side configuration takes precedence over application's
local configuration. However server side configuration can only be used 
to turn off collecting span events.
Closes #443

feat(agent): Honor collect_span_events server config

---

src/newrelic/analytics_events.go
src/newrelic/harvest.go
src/newrelic/harvest_test.go
src/newrelic/metrics.go
src/newrelic/processor.go
src/newrelic/processor_test.go

Very rough prototype for addressing issue $445
1) Adds httperror metrics for new response codes
2) Adds metrics for these endpoints: https://github.com/newrelic/newrelic-php-agent/blob/main/src/newrelic/harvest.go#L139
Needs:
1) Validation
2) Test cases
3) has not added duration, but harvest has a start time, so could theoretically be added

feat(daemon): add supportability metrics for new response codes and for harvest endpoints

---

axiom/util_object.c

Fix what looks like a small typo.

Fix typo passing a char to a const void * argument.

---

agent/scripts/newrelic.ini.template

Found what appears to be a bug in the 'path' for the detect_kubernetes INI config option while investigating for logging.

docs(agent): fix `detect_kubernetes` path in template ini

---

docs/dev_environment.md

Found some incorrect information and formatting issues in the dev_environment.md doc.
Also took some liberty to clean up some other formatting to make it easier to read.

docs: refactor/formatting of dev env guide

---

.github/docker/linux/pr_build.sh
agent/Makefile.frag

PHP embed SAPI (libphp) embeds PCRE library. So does axiom library.
Agent unit tests require both: PHP embed SAPI and axiom library. PHPs
5.5, 5.6, 7.0, 7.1, and 7.2 embed older version of PCRE and this causes
linker to find PCRE symbols in two places: PHP embed SAPI (libphp) and
axiom library. This causes the linker to report a fatal error and abort.
This change allows for multiple definitions and the first definition
found will be used.
Note: PHP embed SAPIs 7.3+ come with PCRE2, which uses different symbol
names and does not create conflict with PCRE embedded in axiom library.

ci: allow multiple symbol defs at agent test link

---

axiom/tests/test_span_queue.c

This is a test I've noticed failing on Jenkins multiple times. This failure is expected if the test process is not receiving much CPU time. Increasing the time window on the test should reduce the number of failures we see due to resource sharing.

fix(axiom/test): increase time window on a time-dependent test

---

agent/Makefile.frag
agent/fw_support.c
agent/fw_support.h
agent/lib_monolog.c
agent/php_execute.c
agent/tests/test_fw_support.c
tests/integration/logging/monolog2/test_monolog_disable_logging.php
tests/integration/logging/monolog3/test_monolog_disable_logging.php

This PR will improve agent performance (save on execution time) because:
* Logging libraries will be instrumented only when the global flag, controling logging feature,
(`newrelic.application_logging.enabled`) is true. This has additional benefit that the value
for `Supportability/Logging/PHP/%s/{enabled|disabled}` metric will also depend on that 
configuration flag.
* Monolog instrumentation will execute only when the at least one flag controlling logging feature (`newrelic.application_logging.forwarding.enabled` or `newrelic.application_logging.metrics.enabled`) 
is true.
* Only the necessary parts of Monolog will be instrumented, depending on flags controlling logging features.

fix(agent): only instrument when logging enabled

---

axiom/nr_limits.h
src/newrelic/collector/client.go
src/newrelic/limits/limits.go
tests/integration/logging/monolog2/test_monolog_log_events_max_samples_stored_invalid1.php
tests/integration/logging/monolog2/test_monolog_log_events_max_samples_stored_invalid2.php
tests/integration/logging/monolog2/test_monolog_log_events_max_samples_stored_invalid3.php
tests/integration/logging/monolog2/test_monolog_log_events_max_samples_stored_invalid4.php
tests/integration/logging/monolog3/test_monolog_log_events_max_samples_stored_invalid1.php
tests/integration/logging/monolog3/test_monolog_log_events_max_samples_stored_invalid2.php
tests/integration/logging/monolog3/test_monolog_log_events_max_samples_stored_invalid3.php
tests/integration/logging/monolog3/test_monolog_log_events_max_samples_stored_invalid4.php

This PR bumps the max log samples to 20000 per minute or 1666 per 5 second fast harvest.
The previous max was 10000 and based on OATS results the new value was selected.
The default value remains 10000.
The new maximum was verified by sending 1666 log events to the collector in a single harvest cycle and confirming this many event were recorded.
Several logging integration tests were updated in accordance with the new max value.
This PR also adds the HTTP response status to the debugging output as newer communications rely on a response code and not the response body to indicate status and errors.  This will help troubleshooting issues.

fix(agent, daemon): Bump max log samples to 20k

---

agent/php_nrini.c

The various "enabled" INI options for agent log handling (forwarding) currently do not specify a handler for displaying the value in "phpinfo()" output so it is handles as a string pointer.  This causes the disabled state (integer 0) to be interpreted as a NULL string so "<no value>" is output instead.
This PR assigned the boolean display handler to these options.
Some previously non-clant-formatted code is corrected as well.

fix(agent): Correct message handler for log options

---

agent/php_environment.c

Previously when parsing the process environment for variables if it was not accessible this generated a warning log message. This commit changes it to a verbosedebug message.

chore(agent): Reduce severity of log message for env vars

---

src/newrelic/limits/limits.go
src/newrelic/processor.go

Simple addition to the daemon to output a notification when the number of applications is approaching the maximum limit.  Also another notification when the number of apps has dropped to a low value.
The intention is to allow for detecting when a new daemon container needs to be spun up to service more applications and also when the number of applications on that daemon container has dropped to a lower threshold.
Also added a debug only message that outputs the current number of applications which might be useful for troubleshooting .

feat(daemon): Add notification on # of apps

---

agent/fw_drupal.c

Fix memory corruption leading to seg fault caused by retrieving the name
of HTTP request method from execute_data after the call to drupal_http_request.
Accessing execute_data after NR_PHP_WRAPPER_CALL leads to memory 
corruption, because execute_data (which can be thought of as a function 
call stack frame) is destroyed after returning from function call and 
therefore it no longer holds a valid information about function args.
This change makes `drupal_http_request` instrumentation compliant with
[Checklist for writing a user function wrapper](https://github.com/newrelic/newrelic-php-agent/blob/main/agent/php_wrapper.h#L64):
> 1. Any call to nr_php_arg_get, nr_php_scope_get, or
>    nr_php_get_return_value_ptr follows any NR_PHP_WRAPPER_REQUIRE_FRAMEWORK_*
>    calls and precedes any …

fix(agent): fix nr_drupal_http_request_exec

---

agent/php_agent.c
agent/php_agent.h
agent/tests/test_agent.c

1) Added 4 new functions for use with OAPI instrumentation:
extern const char* nr_php_zend_execute_data_function_name(
const zend_execute_data* execute_data);
extern const char* nr_php_zend_execute_data_filename(
const zend_execute_data* execute_data);
extern const char* nr_php_zend_execute_data_scope_name(
const zend_execute_data* execute_data);
extern uint32_t nr_php_zend_execute_data_lineno(
const zend_execute_data* execute_data);
2) Added test cases to test new functionality.
3) Updated the following to reflect new OAPI paradigm and add additional checks for robustness:
* #define NR_PHP_USER_FN_THIS()
* nr_php_execute_scope
3) Added unit test cases to test the 4 new functions.  Currently existing functions are being called and used in current tests and will automatically be tested …

feat(agent): Add/Update functions to utilize the OAPI zend_execute_data.

---

agent/newrelic-install.sh
make/release.mk

- Add freebsd to the list of unsupported OSs
- Exit from installation if 32-bit or FreeBSD is detected
- Remove 32-bit and checks
- ZTS removal will be in release following when this installer ships in a release

chore: Update install script to not allow 32-bit or freebsd installs

---

agent/newrelic-install.sh

Ended up with duplicate exit messages if an unsupported arch was detected.

fix(installer): Remove dupe exit msg

---

src/newrelic/collector/client.go
src/newrelic/collector/client_test.go
src/newrelic/collector/collector_test.go
src/newrelic/harvest.go
src/newrelic/infinite_tracing/trace_observer.go
src/newrelic/infinite_tracing/trace_observer_test.go
src/newrelic/processor.go
src/newrelic/processor_test.go

Adds the collection of data usage metrics into a separate channel in the processor. The JSON payload is now extracted from the http client (by passing the command structure by pointer), so we are able to get its size.
There is a maximum amount of data usage metrics that will be stored in between metrics harvests. If many other harvests happen in between a metric harvest, or if the metrics harvest stalls for any number of reasons, usage data will be dropped.
Clarifies, reformats, and updates comments lots of the tests and infrastructure for processor.go/processor_test.go

feat(daemon): add data usage metrics

---

agent/php_execute.c

- `begin` fcall will only show `execute`, since it does not have access to return data.
- `end` fcall will only show `return`, since `execute` will be handled solely by `begin`
Several blocks of functions have been wrapped in 
```c
#if ZEND_MODULE_API_NO < ZEND_8_0_X_API_NO \
|| defined OVERWRITE_ZEND_EXECUTE_DATA
```
statements in order to placate the compiler, since they are defined but never called under the OAPI paradigm.

feat(agent): implement php_execute_show functionality for OAPI

---

agent/php_execute.c

Framework detection (`nr_execute_handle_framework`) not only adds `wraprecs`
but also sets `NRPRG(current_framework)`. It is important to set it before
function is called, because its value affects other instrumentation, e.g.
when datastore segment for SQL operation is ended, a table name modify
function (`nr_php_modify_table_name_fn`) to shorten table name is selected
based on `NRPRG(current_framework)`.
This fixes `frameworks/magento/test_temp_tables.php` and
`frameworks/wordpress/test_site_specific_tables.php` integration tests.

fix(agent): detect framework in oapi's fcall_begin

---

agent/php_execute.c
tests/integration/logging/analog/test_supportability_metric.php
tests/integration/logging/analog/vendor/analog/analog/lib/Analog/Analog.php
tests/integration/logging/cakephp-log/test_supportability_metric.php
tests/integration/logging/cakephp-log/vendor/cakephp/log/Log.php
tests/integration/logging/consolidation-log/test_supportability_metric.php
tests/integration/logging/consolidation-log/vendor/consolidation/log/src/Logger.php
tests/integration/logging/laminas-log/test_supportability_metric.php
tests/integration/logging/laminas-log/vendor/laminas/laminas-log/src/Logger.php

Send `Supportability/Logging/PHP/{framework}/disabled` metric for a few more logging frameworks:
* [Consolidation\Log](https://packagist.org/packages/consolidation/log)
* [laminas-log](https://packagist.org/packages/laminas/laminas-log)
* [CakePHP Logging Library](https://packagist.org/packages/cakephp/log)
* [Analog](https://packagist.org/packages/analog/analog)
The frameworks were selected based on number of downloads on https://packagist.org/. All frameworks exceed 1M downloads.

feat(agent): detect more logging frameworks

---

src/integration_runner/main.go

Hardcode 10000 as the integration_runner's daemon default log event harvest limit that is to be used when connecting to collector.
integration_runner does not use agent settings from integration tests for values in pre-connect/connect payload. It is using pre-cooked app info structure, and any uninitialized fields in that structure, like AgentEventLimits.LogEventConfig.Limit, which is sent in connect payload as the value for event_harvest_config.harvest_limits.log_event_data, gets the default value of 0. Collector accepts and honors this value, which results in integration_runner's daemon and agent to be configured not to collect any log events. This breaks logging integration tests.

test: set LogEventConfig in integration_runner

---

agent/fw_drupal.c
agent/php_newrelic.h
agent/php_rinit.c
agent/php_rshutdown.c
agent/tests/test_fw_drupal.c

Fix `drupal_http_request` instrumentation for PHP 8.0+ by using Observer
APIs `before` callback to add New Relic headers and `after` callback
to finalize external segment with metrics. Observer API instrumentation
requires the external request segment to be created in `before` callback
but be available in `after` callback. Therefore it is made a NRPRG global.

fix(agent): instrument `drupal_http_request`

---

agent/php_txn.c
axiom/nr_txn.c
axiom/nr_txn.h
tests/integration/api/set_appname/test_already_ended.php
tests/integration/api/set_appname/test_appname_license.php
tests/integration/api/set_appname/test_appname_switch_license.php
tests/integration/api/set_appname/test_appname_switch_license_lasp.php
tests/integration/api/set_appname/test_no_license.php
tests/integration/api/set_appname/test_transmit_false.php
tests/integration/api/set_appname/test_transmit_int.php
tests/integration/api/set_appname/test_transmit_true.php
tests/integration/external/curl_multi_exec/test_txn_restart.php

The logging metrics "Supportability/Logging/Forwarding/PHP/<state>" and "Supportability/Logging/Metrics/PHP/<state>"} are supposed to be created once per request.  The previous mechanism did not properly create these metrics if a transaction was started and restarted during a request, or if newrelic_set_appname() was called.
This fix uses a flag within the transaction structure to track if the metrics have been created for the transaction which fixes the previous issue.
Affected integration tests were updated to reflect the metrics are now being created properly.

Fix creating some logging metrics

---

agent/php_execute.c
agent/php_txn.c

More stringent checks are required for PHP 8.1+ prior to querying opcache to prevent warning messages from being thrown. Additionally, the severity level of the messages should be downgraded to `debug`.
1) If `opcache.enable` is true and `opcache.preload`  is not null then call the attempt to instrument the preloaded functions.
2) According to https://www.php.net/manual/en/function.opcache-get-status.php will return either an array or false. Hence https://github.com/newrelic/newrelic-php-agent/blob/main/agent/php_execute.c#L1690 will be either an array or false 
both of which could be valid depending on the state of PHP.
Therefore the warning message:
`User instrumentation from opcache: opcache status information is not an array` is downgraded to debug.
3) clang format picked up a few …

fix(agent): Add more stringent opcache checking.

---

agent/Makefile.frag
agent/config.m4
agent/fw_drupal8.c
agent/php_execute.c
agent/php_newrelic.h
agent/php_rinit.c
agent/php_rshutdown.c
agent/php_txn.c
agent/php_user_instrument.c
agent/php_user_instrument.h
agent/php_user_instrument_hashmap.c
agent/php_user_instrument_hashmap.h
agent/php_user_instrument_hashmap_key.h
agent/tests/test_user_instrument.c
agent/tests/test_user_instrument_hashmap.c

A more performant data structure is used to lookup user instrumentation:
a hashmap with zend function's metadata (lineno, functioname, scope
and filename) as a hash key, and a pointer to a wraprec as a value.
In order to improve performance of the specialized hashmap key matching,
zend_function's metadata is stored in a key as a refcounted zend_string
rather than raw char*. This allows key matching to take advantage of
the following zend_string attributes: length (len) and hash (h) - values for
both are pre-calculated by Zend engine and available for use by the
agent.  Because the agent instruments only a small fraction of all user
functions in a PHP application, there will be more missed hashmap
lookups than hits. Therefore delaying string value comparison until
absolutely necessary (len …

refactor(agent): user instrumentation lookup

---

agent/lib_doctrine2.c
agent/lib_predis.c
agent/php_newrelic.h
agent/php_rinit.c
agent/php_rshutdown.c
tests/integration/predis/test_pipeline.php

Symfony1 instrumentation utilizes the call stack, but should never be run with PHP8+.
Repeat of https://github.com/newrelic/newrelic-php-agent/pull/576 based on a non-forked branch so other PR's can be based on this one.

fix(agent): move globals that utilized the call stack into a global stack

---

agent/php_execute.c
agent/php_observer.c

Consistent with other functions in php_execute, check if txn exists before trying to use it.
The issue occurred during the first request, and because it is the first, the appname is unknown and we don't create a txn.  However, an exception happened in that first request, our exception_hook handler got triggered, and if that is triggered, we always try to close off dangling segments.  In this case, because we didn't check for txn==null, it segfaulted as we tried to access txn elements.
Pr fixes that in two ways, 1) check for txn==null before closing off segments.  2) don't record uncaught exception info generated from our exception_hook handler if a txn is null.
```
2023-01-26 21:03:16.816 +0000 (29813 29813) verbosedebug: RINIT processing started
2023-01-26 21:03:16.816 +0000 (29813 …
```

fix(agent): Ensure txn exists before we try to reference it.

---

agent/fw_wordpress.c

move NR_GET_RETURN_VALUE_PTR before NR_PHP_WRAPPER_CALL
Cleanup conditional compilation to be more readable

fix(wordpress): fix unbound memory allocation when wordpress tags off

---

agent/scripts/newrelic.ini.template

Update the INI documentation with warnings and instructions about CLM pulling long filepaths that result in exceeding the max message size limit the daemon adheres to.

docs(agent): update INI documentation with CLM warnings

---

agent/fw_cakephp.c
agent/fw_drupal.c
agent/fw_drupal8.c
agent/fw_laminas3.c
agent/fw_laravel.c
agent/fw_lumen.c
agent/fw_magento2.c
agent/fw_mediawiki.c
agent/fw_slim.c
agent/fw_symfony4.c
agent/fw_wordpress.c
agent/fw_yii.c
agent/php_wrapper.h
agent/tests/test_php_wrapper.c

For OAPI, wrapping default makes all wrapped special functions execute during func_end.  This caused issues since to customize txn naming per framework, PHP agent uses the order in which functions
are processed, NR_NOT_OK_TO_OVERWRITE/NR_OK_TO_OVERWRITE, and whether it is
called either before or after NR_PHP_WRAPPER_CALL (for pre PHP 8+) or whether
it is called in func_begin or func_end (for PHP 8+ / OAPI). By defaulting to calling all callbacks "after" during func_end, it changed the order in which nr_txn_set_path was being set.  To fix this, we need to verify which callback functions set the txn before NR_PHP_WRAPPER_CALL and which set it after, and have the wrapped functions act similarly to call before/after.
This PR 
1) reviewed all frameworks (exceptions listed below) and use of …

fix(agent): Explicitly call some special function instrumentation in oapi func_begin for txn naming.

---

.github/workflows/agent-build.yml
agent/php_includes.h
agent/php_nrini.c
agent/tests/tlib_php.c
files/Dockerfile

Overview:
- cc3c88e5eb2e8b0a2fd85494fea22fe71b9220a1 updates Docker to pull the 8.2 image
- 026e0ba305a70f2ef00639b776c1ca5084e6893a adds the Zend API No
- 3946ab3f0f4ab6d32e019db426e714972cc04cd9 addresses the removal of the [num_additional_modules](https://github.com/php/php-src/blob/PHP-8.2/UPGRADING.INTERNALS#L109)
- 9cb040aab11a9055b032075e39edb1fb5b596396 addresses the addition of a `type` to [REGISTER/UNREGISTER_INI_ENTRIES](https://github.com/php/php-src/blob/PHP-8.2/Zend/zend_ini.h#L199)
- dabca0db641e83c859e0e2fbc8f2bf5504811ddf updates GHA workflow build considerations

Initial build changes for 8.2

---

Makefile
agent/config.m4
axiom/Makefile
axiom/tests/Makefile
make/config.mk
make/vendor.mk

Give the user an option to use `protobuf-c` from location alternative to
`vendor` subdirectory via `PROTOBUF_C_PREFIX` environmental variable.
`$PROTOBUF_C_PREFIX/bin` needs to have `protoc-c` binary, 
`$PROTOBUF_C_PREFIX/include` needs to have `protobuf-c/protobuf-c.h`
header file and `$PROTOBUF_C_PREFIX/lib` needs to have `libprotobuf-c.a`. 
By default agent's build system will try to look for `protobuf-c` dependency
in location returned by `pkg-config libprotobuf-c --variable=prefix`, a
location where `protobuf-c` is installed in the system via package
managers. If that location does not have `protobuf-c`, agent's build
system will fallback to using `protobuf-c` from `vendor` directory. This
enhancement speeds up agent build because neither `vendor/protobuf` nor
`vendor/protobuf-c` …

build: enhance pcre and protobuf-c dependencies

---

.github/workflows/release-build.yml

Update release-build workflow to:
* only build release artifacts for PHP 8.2 on amd64 arch
* use pre-built container image instead of building the image on the fly
each time the workflow needs to run

ci: make release-build build for PHP 8.2

---

axiom/nr_app_harvest.c

To maintain New Relic's PHP Agent compatibility with older runtime platforms, use GNU's Assembler's [as](https://sourceware.org/binutils/docs/as/index.html) [.symver](https://sourceware.org/binutils/docs/as/Symver.html) directive to pin glibc's symbols to versions compatible with RHEL7, which uses glibc version 2.17.

build: pin libc's symbol versions

---

.github/workflows/release-build.yml

Set the build number part of the agent version to make release artifacts, generated by release-build workflow, compatible with the rest of the release pipeline.

ci: version in release build needs build number

---

Makefile
agent/config.m4
axiom/tests/Makefile
make/config.mk

By default let the agent link to whatever libpcre is available on the system (most likely a shared object). However for release builds the agent needs to link with a static version of libpcre to ensure it runs on all Linux distros. This is needed because different Linux distributions use different names for the shared object and its impossible to link to a shared object that works universally on all Linux distributions. If PCRE_STATIC is set to yes, agent's build system will enforce linking to static version of libpcre and if it is not available, the build will abort.
Supplements #613

build: don't enforce linking to static libpcre

---

agent/php_call.h
agent/php_file_get_contents.c
agent/php_nrini.c
agent/php_zval.h
axiom/util_memory.c

This PR addresses compilation warnings/errors encountered when building the agent with GCC 12.
```bash
In file included from util_memory.c:15:
util_memory.c: In function 'nr_realloc':
util_logging.h:223:7: error: pointer 'oldptr' may be used after 'realloc' [-Werror=use-after-free]
223 |       nrl_send_log_message(NRL_ERROR, __VA_ARGS__); \
|       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
util_memory.c:100:5: note: in expansion of macro 'nrl_error'
100 |     nrl_error(NRL_MEMORY, "failed to reallocate %p for %zu bytes", oldptr,
|     ^~~~~~~~~
util_memory.c:98:9: note: call to 'realloc' here
98 |   ret = (realloc)(oldptr, newsize);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
```bash
In file included from …
```

build: cleanup code to build with gcc12

---

agent/newrelic-install.sh

This PR added the PHP 8.2 API to the list of extension artifacts to check when verifying the integrity of the install payload.
Also added a comment to the relevant section of code to make it more obvious it needs to be changed the next time the script is updated.

fix(installer): Add php82 api

---

src/newrelic/processor_test.go

Some tests were assuming that the time the metrics were created would be the same time that the metrics were sent. This non-deterministically fails if the brief period between those times in the test spanned a unix time step. ([code that does this seen here](https://github.com/newrelic/newrelic-php-agent/blob/main/src/newrelic/metrics.go#L282))
This PR fixes that assumption and properly grabs both the different times for creation of the "truth" metrics object.

test(daemon): fix non-deterministic failures

---

make/release.mk

Refactor release targets to give more flexibility in building them 
without triggering legacy release workflow.
Separate release-installer-script and release-installer-iutil targets
from release-installer target. This is needed because newrelic-install
is not a binary artifact, which does not depend on platform arch, and
newrelic-iutil is a binary artrifact, which depens on platform arch.
Separating these targets out simplifies building agent release when
using containers as build platform.
Separate release-version target from release target. This is needed
when VERSION and COMMIT artifacts are needed without the need to do
a full build (which build the daemon and the agent for all PHPs), e.g.
while testing release workflow.
Add a target for building the agent for a given PHP version. …

build: refactor release targets

---

src/integration_runner/main.go
src/stressor/main.go

Fixes two minor daemon issues that newer go test versions (1.10+) dislike. ([further discussion here](https://github.com/golang/go/issues/23062))
1) format directives in Fprintln. There is an Fprintln call that should be an Fprintf because it contains formatting directives. Previously, the directive was ignored and the additional arguments were added to the end of the string.
2) passing an extra newline to Fprintln. Go dislikes Fprintln being passed a string that ends in a newline. To achieve the exact same previous functionality, it is now a Fprint call with an additional newline character.

style(daemon): go test warnings

---

agent/php_call.c

@lavarou 's great research and findings:
While I was looking for some information about -Wclobber and learning about zend_try/zend_catch I found these two interesting resources:
https://github.com/php/php-src/pull/5151 - this basically shows that PHP team is aware of issues caused by -Wclobber and basically turn these warnings off (I don’t know if it’s good or bad that PHP is ignoring compiler warnings though; maybe they know what they’re doing)
https://github.com/php/php-src/blob/master/main/streams/userspace.c#L335-L340 - this is an example in PHP source code how zend_call_method_if_exists is called. It is a nice little trick of using an automatic variable to store user function call result. Based on this I came up with this idea: …

use local variable for retval to avoid clobbering

---

agent/scripts/newrelic.ini.template
src/daemon/flags_test.go
src/newrelic/log/log.go
src/newrelic/log/log_test.go
src/newrelic/processor.go

This PR adds a new log level for the daemon called "healthcheck".  It is between "debug" and "info" in verbosity. 
If enabled this log level will currently output a daemon log message of type "HealthCheck" which will output the current number of applications connected to the agent as well as the maximum number of allowed applications.
The format of the line is:
```log.Healthf("current number of apps is %d of a max of %d", numapps, limits.AppLimit)```
where ```numapps``` is the current number of applications and ```limits.AppLimit``` is the compile-time limit for the number of applications a daemon instance will allow.

feat(daemon): Add loglevel for daemon health

---

agent/php_internal_instrument.c
tests/integration/external/curl_multi_exec/test_curl_multi_exec_params.php

Should fix #605 
Converting second parameter to `zval` should match function requirements of `php-src` `curl_multi_exec`:
https://github.com/php/php-src/blob/8d5953c002e9acccc373e96998ab62ab64990fa4/ext/curl/multi.c#L204-L207

fix(agent): fix parsing curl_multi_exec params

---

src/integration_runner/main.go
src/integration_runner/reports.go
src/newrelic/integration/test.go

This commit adds a 'warn' test result which is intended to be used to represent tests which could not be run due to something not being correct in the environment.  
The intention is 'skip' is for tests which cannot be run because of the PHP version or some other expected condition which would make the test not run in all environments.   However, currently 'skip' is used to also represent when a test which is expected to run could not run due to a misconfiguration of the environment.  This can cover up potential test run deficiencies.
The use of 'warn' means the test environment is mis-configured. 
A new integration_runner boolean option 'warnisfail' will cause any warnings to be treated as a failure and the integration_runner will exit with a non-zero exit code to signify the failure. …

feat(integration_runner): Add 'warn' test result

---

.github/workflows/test-agent.yml

Use docker/setup-qemu-action to enable arm64 emulation and pin tonistiigi/binfmt image version. Use repository variable BINFMT_IMAGE_VERSION to control which version of this dependency will be used.

refactor: use GitHub Action to enable arm64

---

agent/newrelic-install.sh

Expand `pi_php8` variable correctly when checking aarch64 support.

fix: typo in install-newrelic script

---

agent/php_minit.c
tests/integration/external/curl_exec/test_dt_enabled_cat_enabled.php

This PR will throw a warning message in the agent log about the CAT + DT conflict, suggest to the end user that they modify the setting, and will modify the `cross_process_enabled` INI value for the duration of the transaction to safeguard against any potential holes in the code that could allow both CAT and DT functionality present in the same transaction.
This PR does not modify the INI file, and checking INI settings (with `phpinfo()` or `php -i`) will not show this change reflected. As far as I'm aware, that's only possible by modifying the INI file itself, which is not something we should do.
A test has been added to verify this scenario.

fix(agent): disable CAT when DT enabled

---

.github/workflows/test-agent.yml

`make` is no longer an entry point in enhanced make-php images.

ci(test-agent): use new make-php images

---

agent/newrelic-install.sh

Log a deprecation warning when detecting php 5.5 or 5.6 when running the newrelic-install script

feat: deprecate php 5.5 and 5.6

---

agent/fw_drupal8.c
agent/php_user_instrument.c
agent/php_user_instrument.h
agent/php_wrapper.c
agent/php_wrapper.h
agent/tests/test_user_instrument.c
tests/integration/frameworks/drupal/mock_module_handler.php
tests/integration/frameworks/drupal/mock_page_cache_get.php
tests/integration/frameworks/drupal/test_invoke_all_with.php

Adds a transient argument to `nr_php_add_custom_tracer_named`, so that when adding a tracer from name we can decide the transience at creation. Previously, all tracers from name were non-transient. To facilitate this change, an additional `nr_php_wrap_*` function has been created: `nr_php_wrap_user_function_with_transience`. This wrapping function takes transience as a parameter and properly plumbs it into `nr_php_add_custom_tracer_named`. Due to this change and to reduce code duplication, `nr_php_wrap_user_function` simply calls `nr_php_wrap_user_function_with_transience` with `transience` argument value set to `NR_WRAPREC_NOT_TRANSIENT`. This effectively works as a default parameter and keeps the top-level API consistent for all previous instrumentation.
Additional tests have been added …

fix: rework generic callable instrumentation to properly handle transience

---

.github/workflows/run-integration-tests.yml

An on-demand workflow that will run integration tests for PHPs 8.0, 8.1 and 8.2 on gnu and musl platforms on x86_64 and aarch64 architectures. This workflow runs integration tests only because unit tests as well as custom events limits tests and LASP tests are already part of the test-pull-request workflow.
It is expected that running tests on aarch64 architecture will cause test failures because tests run slower on emulated platform and more spans are generated. aarch64 environment needs some adjustments - maybe experiment with `expensive_node_min`.

ci: add on-demand run-integration-tests workflow

---

agent/fw_drupal8.c

Since this is called with every request, the message, when triggered, can fill up the logs. It's more appropriate for it to be a `verbosedebug` level similar to the majority of other drupal messages.  Generally, msgs that have a probability of logging with every request should not be info level.

fix(agent): Update drupal msg logging level

---

.github/workflows/run-integration-tests.yml

Fix `experimental` flag in strategy matrix of on-demand run-integration-tests workflow. It is expected that running tests on aarch64 architecture will cause test failures because tests run slower on emulated platform and more spans are generated and therefore this arch is marked as `experimental` and failed tests on that arch will not mark the whole workflow as failed.

ci: fix on-demand run-integration-tests workflow

---

.github/workflows/test-agent.yml
axiom/nr_daemon_spawn.c

Update `test-pull-request` workflow with steps to generate [`gcov`](https://gcc.gnu.org/onlinedocs/gcc/Gcov.html) code coverage reports for `agent` and `axiom` and upload them to [codecov.io](https://app.codecov.io/gh/newrelic/newrelic-php-agent). Since there are no differences between `gnu` and `musl` platforms as well as `amd64` and `arm64` architectures, reports are only generated for `gnu` on `amd64` for all supported PHP versions.

ci: integrate code coverage reporting

---

files/Dockerfile

Fix the Dockerfile used by `make dev-shell` in development.
Upstream PHP docker images have migrated to Debian 12 bookworm, which modifies the sources location as well as dependency names.
This fix only resolves running PHP versions 8.0+.

chore: make dev-shell compatible with Debian 12

---

.github/workflows/code-coverage-baseline.yml

Add a workflow to generate and upload code coverage data for selected
origin and ref to establish code coverage baseline. This workflow is
useful to establish code coverage baseline for long lasting branches
that are target of pull requests.

ci: add code-coverage-baseline workflow

---

agent/newrelic-install.sh

When installing the agent on unsupported version of php on specific arch, include link to docs in the error message. Small output change as I personally got stuck here. The other output on incompatibility always include the link so I copied it into this error message.
This is #686 moved to upstream.

feat(newrelic-install): include link to docs in install error message

---

.github/workflows/make-agent.yml
.github/workflows/make-for-platform-on-arch.yml
.github/workflows/make-integration-tests.yml
.github/workflows/run-integration-tests.yml

Refactor run-integration-tests workflow into reusable workflows to allow fine tuning which runners to use for which job depending on architecture. Experiments showed that building on default runner but using larger runner (4cores) for running integration tests on arm64 achieves best time/cost results. I.e. using larger runners to build on arm64 cuts the workflow runtime from about 30 minutes to about 20 minutes and therefore does not seem necessary. However, using larger runners to run test on arm64 is necessary not as much for time savings but for performance - without larger runners, tests run too slow and more spans are captured which causes actual results not to match test expectations.

ci: refactor run-integration-tests to use larger runners

---

agent/tests/valgrind-suppressions

A call to `zend_map_ptr_reset` in `zend_deactivate` triggers `Invalid read of size 8` valgrind error in test_redis during `tlib_php_request_eval_expr` and `nr_php_zval_free` in the last php request lifecycle when Observer API is used to hook into Zend engine. This error is triggered on all PHPs with this patch: https://github.com/php/php-src/commit/ff62d117a35509699f8bac8b0750a956914da1b7

suppress `Invalid read` error in test_redis

---

agent/php_wrapper.c

Build fails when PHP 5.x ifdefs are missing - `zend_string` type is not defined for PHP 5.x.

fix build for PHP 5.x

---

agent/php_wrapper.c
agent/php_wrapper.h

When wrapping a user function do not add special instrumentation is ANY special instrumentation (before/after/cleanup) has already been set. This approach matches pre-oapi instrumentation.

fix(agent): set oapi callbacks the right way

---

agent/fw_drupal.c
agent/fw_drupal8.c
agent/fw_drupal_common.c
agent/fw_drupal_common.h
agent/php_newrelic.h
agent/php_rinit.c
agent/php_rshutdown.c
agent/php_wrapper.c
agent/php_wrapper.h

In addition to OAPI Drupal 9.4 support, this PR does some refactoring:
1. The hook stacks have been renamed from `module_invoke_all` to
`invoke_all` to be more aligned with the name of Drupal functions that
can now push to those stacks.
2. The generic wrapper function (originally added when Drupal 9.4
instrumentation was introduced) has been updated to support OAPI.
3. `nr_php_wrap_callable_before_after_clean` has been introduced as a
parallel for `nr_php_wrap_user_function_before_after_clean`. To
facilitate this, many of the internals have been extracted to a common
function.
4. Speaking of, lots of the maintenance of the Drupal's hook stacks has
been extracted to common functions to reduce code reuse

feat(agent): instrument Drupal 9.4 hooks with oapi

---

agent/php_execute.c
tests/integration/frameworks/wordpress/test_wordpress_do_action.php8.php

When instrumenting wordpress/drupal hooks, we want to instrument the hook function calls, which are dispatched by php's call_user_function_array. This php function (cufa for short) is flattened/inlined, so to determine if we are in a function called by a cufa call, we need to check the opcodes of the caller to the current function. If the caller is a php internal function, checking these opcodes was not safe and lead to invalid reads. As such, before reading the opcodes, we first check if the caller is a user function. We only want to instrument cufa calls from user functions anyway.

fix: add guards to oapi cufa opcode check

---

agent/php_call.c
tests/integration/frameworks/wordpress/test_wordpress_apply_filters.php8.php
tests/integration/frameworks/wordpress/test_wordpress_do_action.php8.php

Calls to `call_user_function` (in PHP 8.0 and 8.1) and `zend_call_method_if_exists` (in PHP 8.2+) need to be wrapped by the `zend_try`/`zend_catch`/`zend_end_try` block, which use [`setjmp`](https://linux.die.net/man/3/setjmp) and [`longjmp`](https://linux.die.net/man/3/longjmp), because according to [`call_user_func()`](https://www.php.net/manual/en/function.call-user-func.php):
> Callbacks registered with functions such as `call_user_func()` and [`call_user_func_array()`](https://www.php.net/manual/en/function.call-user-func-array.php) will not be called if there is an uncaught exception thrown in a previous callback.
So if we call something that causes an exception, it will block us from future calls that use `call_user_func` or `call_user_func_array`. Valgrind showed the agent and/or …

fix(agent): wrap zend_try in a func to avoid clobbering

---

.github/workflows/test-agent.yml

1. [always finish all integration tests](https://github.com/newrelic/newrelic-php-agent/commit/a8e635ce6255eddda628732bcca68f4c0bbf26bc) 
Don't cancel all in-progress and queued integration tests jobs if one of them
fails.
2. [trigger job for each pull request](https://github.com/newrelic/newrelic-php-agent/commit/48b8f8e9dbde630280297a1bc40945ca31734d8f) 
Test all pull requests targeting any branch, not only targeting `main`, `dev`
and `oapi` branches.
3. [fix 'Enable arm64 emulation' in agent-unit-test](https://github.com/newrelic/newrelic-php-agent/commit/b3f104808bb445a09dc370867a0d3a7b7b454f53)
There's no need to enable arm64 emulation when not testing arm64 agent. Use
the right way to enable arm64.

ci: make test-pull-request more useful

---

tests/integration/predis/test_basic_reporting_disabled.php
tests/integration/predis/test_instance_basic.php
tests/integration/predis/test_txn_restarted.php

This PR migrates the `predis` tests from multiverse to be included in the regular agent integration tests.
Tested with PHP 5.5+.

tests(agent): add more predis integration tests

---

agent/php_execute.c
tests/integration/external/guzzle6/test_cat.php
tests/integration/external/guzzle6/test_dt.php
tests/integration/external/guzzle6/test_dt_newrelic_header_disabled.php
tests/integration/external/guzzle6/test_dt_synthetics.php
tests/integration/external/guzzle6/test_dt_synthetics_logging_off.php
tests/integration/external/guzzle6/test_no_cat_no_dt.php
tests/integration/external/guzzle7/test_cat.php
tests/integration/external/guzzle7/test_dt.php
tests/integration/external/guzzle7/test_dt_newrelic_header_disabled.php
tests/integration/external/guzzle7/test_dt_synthetics.php
tests/integration/external/guzzle7/test_no_cat_no_dt.php
tests/integration/predis/test_basic.php
tests/integration/predis/test_basic_logging_off.php
tests/integration/predis/test_basic_reporting_disabled.php
tests/integration/predis/test_pipeline.php
tests/integration/predis/test_pipeline_atomic.php
tests/integration/predis/test_pipeline_fire_and_forget.php
tests/integration/predis/test_pipeline_fire_and_forget_logging_off.php

Use files that more uniquely identify Guzzle 5, and Guzzle 6. Because 
the file used to identify Guzzle 5 is unique to Guzzle 5, Guzzle 4-5
supportability metrics are no longer generated when predis is detected.
Guzzle 4-5 supportability metrics is also not generated when Guzzle 6
or Guzzle 7 are detected.

refactor(agent): improve guzzle detection

---

src/newrelic/integration/parse.go
src/newrelic/integration/test.go

Adds a new feature (`EXPECT_SPAN_EVENTS_LIKE`) for the `integration_runner` which allows testing for the existence of a set of spans in the actual spans created.  It differs from `EXPECT_SPAN_EVENTS` in that it is not necessary to list ALL expected spans.  For tests involving PHP frameworks the number of generated spans can be in the hundreds so it is not practical to use `EXPECT_SPAN_EVENTS` and thus `EXPECT_SPAN_EVENTS_LIKE` was added.
Here is an example:
```
/*EXPECT_SPAN_EVENTS_LIKE
[
[
{
"category": "generic",
"type": "Span",
"guid": "??",
"traceId": "??",
"transactionId": "??",
"name": "WebTransaction\/Action\/dispatch",
"timestamp": "??",
"duration": "??",
"priority": "??",
"sampled": true,
"nr.entryPoint": true,
"transaction.name": "WebTransaction\/Action\/dispatch"
},
{},
{ …
```

feat(testing): Implement EXPECT_SPAN_EVENTS_LIKE

---

axiom/nr_segment.c
axiom/tests/test_segment.c

When using 8T the 'parentId' intrinsics attribute was not being set for
the root span of a service to a value based on the inbound header.  This caused
fragmented traces.  This commit added the required 'parentId' attribute.
Normal DT (not 8T) was working correctly because the 'parentId' was
being added to a span returned from nr_segement_to_span_event()
in a different code path dedicated to JSON creation starting with
nr_segment_tree_finalise().
A test in test_segment.c was modified to check that the 'parentId'
is correctly set based on the inbound DT header.

fix(agent): Fixes 8T distributed traces

---

tests/integration/external/drupal7/test_bad_params_integer_headers.php
tests/integration/external/drupal7/test_bad_params_integer_headers.php8.php
tests/integration/external/drupal7/test_bad_params_null_headers.php8.php

External metrics should not be generated when call to `drupal_http_request` fails due to uncaught error. This works correctly in PHPs 8+, when Observer API is used to hook into Zend Engine but doesn't work correctly for previous method of hooking into Zend Engine hence two flavors of tests.
Additional notes from @zsistla: 
For drupal7, external metrics were getting generated inconsistently for uncaught exception cases. Going forward, the agent will not generate external segment metrics in all cases where an exception occurred.
The 2 tests failed when instrumenting with observer api because an uncaught error occurred which made the drupal_http_request end function handling not get called so the external METRICS were not getting generated.
The agent actually handled this inconsistently in …

tests: fix metrics expectation in drupal tests

---

agent/fw_cakephp.c
agent/fw_drupal.c
agent/fw_drupal8.c
agent/fw_laravel.c
agent/fw_lumen.c
agent/fw_magento2.c
agent/fw_symfony4.c
agent/fw_wordpress.c
agent/fw_yii.c
agent/lib_doctrine2.c
agent/lib_predis.c
agent/php_user_instrument.c
agent/php_user_instrument.h
agent/php_wrapper.c
agent/php_wrapper.h
agent/tests/test_php_wrapper.c
agent/tests/test_user_instrument.c

There still exists a default wrapper, `nr_php_wrap_user_function`, which (for OAPI) creates an 'after' wraprec that is non-transient and creates an `InstrumentedFunction` metric. Before this PR, there was the option to create 'before', 'after', and 'clean' wrappers and define the transience.
This PR extends the options available when creating a wraprec to no longer create the InstrumentedFunction metric. It wraps this option with the other bool option (transience) into an options struct.
Additionally, if the top-most default, `nr_php_wrap_user_function`, is not used, every single option must be defined ('before', 'after', 'clean', transience, and instrumented metric). This takes the concept that if a single one of these fields is non-default, it is much more likely that other fields will …

feat: optional instrumentated function metric

---

agent/scripts/newrelic.ini.template

Adds the `newrelic.application_logging.local_decrorating.enabled` INI value to the template `newrelic.ini`.

chore(agent): Adds log decoration INI value

---

agent/php_user_instrument.c
tests/integration/frameworks/drupal/test_invoke_all_with.php
tests/integration/frameworks/wordpress/test_wordpress_apply_filters.php

Prevent adding transient wraprecs for already wrapped transient functions by checking if wraprec already exists in the hashmap. Additionally prevent adding transient wraprecs for if the transient function is already wrapped as non-transient function by checking if wraprec already exists in the linked list.
For non-transient wrappers (standard instrumentation), the wrapper
is stored in both the hashmap and linked-list. For transient wrappers,
the wrapper is only stored in the hashmap. HOWEVER! non-transient
wrappers MAY only be in the linked-list. This normally happens if it
is wrapping a function that hasn't been loaded by PHP yet. Once the
function is loaded, there are many hooks to ensure the wrapper is also
added to the hashmap.
The implications of the above are: For non-transient …

fix(agent): fix wrapping transient user functions

---

src/newrelic/processor.go

The DefaultData harvest is only for data which can't/won't have its rate dictated by the Collector. All other data, which can have its own individual report rate, must be handled outside of the DefaultData block. SpanEvents and LogEvents already have their rates handled as such ([here](https://github.com/newrelic/newrelic-php-agent/pull/745/files#diff-d34a767f316aaeded794ac3a231f867d3ffb42de19365ed338eace17f5876d94R740) and [here](https://github.com/newrelic/newrelic-php-agent/pull/745/files#diff-d34a767f316aaeded794ac3a231f867d3ffb42de19365ed338eace17f5876d94R748)), and therefore should not also be reported with DefaultData. Because the DefaultData block was not resetting the above event containers, duplicate harvests were possible.

fix(daemon): remove duplicate harvests

---

agent/php_newrelic.h
agent/php_nrini.c
agent/scripts/newrelic.ini.template

Adds the required INI values for APM log forwarding context data.
This PR adds the INI value parsing and data structures needed to hold these values.
The integration of these values into the capture and forwarding of context data will occur in following PRs.

feat(agent): Adds INI for log context attributes

---

agent/php_internal_instrument.c
tests/integration/mysqli/test_null_connect_proc.php
tests/integration/mysqli/test_null_construct_oo.php
tests/integration/mysqli/test_null_rc_oo.php
tests/integration/mysqli/test_null_rc_proc.php
tests/integration/mysqli/test_null_stmt_construct.php

Certain wrapped mysqli functions allow null values to be passed for optional values on PHP 8.1+. 
This PR fixes the issue of the agent not properly expecting these null values in zpp resulting in deprecation warnings being thrown.

fix(agent): Resolve mysqli deprecation warnings on PHP 8.1+

---

agent/php_newrelic.c

Aligned zpp and arginfo.
When PHP8+ is built in debug mode, zpp/arginfo mismatches are now Fatal Errors. Fixed the mismatches that existed in the code base.
For reference: https://www.phpinternalsbook.com/php7/extensions_design/php_functions.html

fix(agent): Addressed zpp/arginfo mismatches

---

tests/integration/external/guzzle5/test_spans_external.php
tests/integration/external/guzzle5/test_spans_external.php5.php
tests/integration/external/guzzle6/test_spans_are_created_correctly.php
tests/integration/external/guzzle6/test_spans_are_created_correctly.php5.php
tests/integration/external/guzzle7/test_spans_are_created_correctly.php

guzzle integration tests are flaky - they expect span for a call to `new Client();`
however when `transaction_tracer.detail` is set to 0, the agent sometimes drops it.
On the other hand when `transaction_tracer.detail` is set to 1, the agent
generates many more spans. Take advantage of `EXPECT_SPAN_EVENTS_LIKE` and only look
for limited number of spans: root and external.

tests: fix guzzle integration tests

---

src/newrelic/integration/parse.go
src/newrelic/integration/test.go
src/newrelic/metrics.go
src/newrelic/metrics_test.go
tests/integration/logging/analog/test_supportability_metric.php
tests/integration/logging/cakephp-log/test_supportability_metric.php
tests/integration/logging/consolidation-log/test_supportability_metric.php
tests/integration/logging/laminas-log/test_supportability_metric.php

Integration tests sometimes don't care about the exact set of metrics that are being sent (particularly around things like datastore metrics); what is really interesting is that the framework is detected, the transaction is named correctly, and that there aren't errors. This adds a new `EXPECT_METRICS_EXIST` section which is simply a newline separated list of metric names that will be searched for: if any don't exist, the test will fail.
For example:
```php
<?php
/*EXPECT_METRICS_EXIST
Supportability/framework/WordPress/detected
*/
?>
```
This asserts that the test will generate
`Supportability/framework/WordPress/detected` metric, but doesn't assert anything else about the metric table.
---------

tests: add `EXPECT_METRICS_EXIST` to integration tests

---

tests/include/helpers.php
tests/integration/ini/test_transaction_tracer_max_segments.php
tests/integration/ini/test_transaction_tracer_max_segments_nested.php
tests/integration/ini/test_transaction_tracer_max_segments_nested.php5.php
tests/integration/ini/test_transaction_tracer_max_segments_no_cap.php
tests/integration/ini/test_transaction_tracer_max_segments_with_datastore.php
tests/integration/ini/test_transaction_tracer_max_segments_with_datastore.php5.php

1. [Force non-zero duration of helper user function](https://github.com/newrelic/newrelic-php-agent/pull/781/commits/3b30afde42664a5fb00408a9e0f1d43e4770cbae)
When tests execute fast enough, the helper function's segment start time and end time are equal and this causes the segment to be dropped (see [here](https://github.com/newrelic/newrelic-php-agent/blob/1563e8045968fe0c6ee228c566ca080afceba6c1/axiom/nr_segment_traces.c#L371-L378)). However, some integration tests have inconsistent test expectation in expected transaction traces (all tests that use `force_transaction_trace`, defined in `tests/include/helpers.php`, e.g. many tests in `tests/integration/attributes`). On one hand, wildcard match is used for trace details (e.g. [here](https://github.com/newrelic/newrelic-php-agent/blob/156 …

tests: make tests deterministic

---

agent/php_environment.c

Agent should not emit a warning message if the Docker ID was not detected in `/proc/self/mountinfo`. 
Non-dockerized and Non-docker V2 applications will not have this value.

fix: remove warning message for `NULL` Docker ID

---

agent/php_agent.h
agent/php_execute.c
axiom/tests/test_strings.c
axiom/util_strings.h

Speed up speed library/framework detection by performing a suffix match on the 'magic' file pattern with case insensitive string comparison instead of a substring search within a lowercased filename. This is possible because all of the 'magic' file search patterns patterns are right anchored.

refactor(agent): improve magic file recognition performance

---

agent/fw_wordpress.c
agent/fw_wordpress.h
agent/php_minit.c
agent/php_mshutdown.c
agent/php_newrelic.h
agent/php_rinit.c
agent/php_rshutdown.c

Improve agent's performance by compiling `wordpress_hook_regex` once per process at MINIT rather than on every request at RINIT, (and be clean up at MSHUTDOWN rather than RSHUTDOWN).

refactor: compile wordpress hook regex at minit

---

agent/fw_wordpress.c
agent/php_newrelic.h
agent/php_rshutdown.c

Improve agent's performance by caching WordPress 'clean_tag' values of transient tags (hooks) rather than cleaning them with regex matching each time they are encountered in a request.

refactor: cache wordpress clean tag values

---

agent/fw_wordpress.c
agent/php_agent.h
axiom/tests/test_matcher.c
axiom/util_matcher.c
axiom/util_matcher.h
axiom/util_strings.h

A couple of suggestions to #765:
1. Save time by using pre-calculated string lengths vs calling strlen whenever possible
2. Move `nr_file_basename` as `nr_wordpress_strip_php_suffix` back to `fw_wordpress.c`

refactor: suggestion to #765

---

tests/integration/redis/test_instance_list.php
tests/integration/redis/test_lget.php
tests/integration/redis/test_list.php
tests/integration/redis/test_list_logging_off.php
tests/integration/redis/test_lrem.php
tests/integration/redis/test_lremove.php

`lGet` and `lRemove` are deprecated functions that no longer run on later versions of the Redis extension. Pin the tests to the last known working version and gate via SKIPIF.

tests: fix deprecated redis function tests

---

agent/fw_drupal8.c
agent/fw_hooks.h
agent/fw_laminas3.c
agent/fw_laravel.c
agent/fw_lumen.c
agent/fw_slim.c
agent/fw_symfony4.c
agent/fw_wordpress.c
agent/lib_doctrine2.c
agent/lib_guzzle4.c
agent/lib_guzzle6.c
agent/lib_mongodb.c
agent/lib_monolog.c
agent/lib_phpunit.c
agent/lib_predis.c
agent/php_agent.c
agent/php_agent.h
agent/php_execute.c
axiom/nr_php_packages.c
axiom/nr_php_packages.h
axiom/tests/test_txn.c

This PR extracts the version for the following PHP packages and adds the package name and version to the transaction.
- Drupal 8, 9, 10 (`drupal/core`)
- Guzzle 6 (`guzzlehttp/guzzle`)
- Slim (`slim/slim`)
- PHPUnit (`phpunit/phpunit`)
- Predis (`predis/predis`)
- Wordpress 
In addition, this PR also sends information about the following PHP packages. For the packages that are being added without a version, an empty string will be sent as the version:
- Laminas without version information (`laminas/laminas-mvc`)
- Laravel with version information (`laravel/framework`)
- Lumen without version information (`laravel/lumen-framework`)
- Symfony without version information (`symfony/http-kernel`)
- Doctrine without version information (`doctrine/orm`)
- MongoDB without version information …

feat(agent): extract version for php packages

---

agent/php_execute.c
agent/php_user_instrument.c
agent/php_user_instrument.h
agent/php_wrapper.c
agent/php_wrapper.h
agent/php_zval.h
agent/tests/test_user_instrument.c
tests/integration/frameworks/drupal/skipif.inc
tests/integration/frameworks/drupal/test_invoke_all_with.php
tests/integration/frameworks/drupal/test_module_invoke_all.php

`nr_php_wrap_generic_callable` is used to create transient wraprecs for callables which **_don't require to be named_**. This assumption makes it possible to stay DRY and reuse `nr_php_zval_to_function` in lieu of complex pattern matching for the type of callable. This reduces agent's performance overhead as it now uses `nr_php_wrap_callable` always instead of sometimes using `nr_php_wrap_user_function_with_transience(IS_TRANSIENT)`. This is an alternative to #665 which obsoletes and removes #679 and makes #770 no longer needed.
TL:DR; The agent's performance overhead when `nr_php_wrap_user_function_with_transience(IS_TRANSIENT)` is used comes from the need to walk the linked list of named wraprecs in `nr_php_add_custom_tracer_named` …

refactor: improve performance of wrap_generic_callable

---

agent/fw_wordpress.c
agent/php_user_instrument.h

Improve agent's performance by figuring out the plugin/theme name at the point an action or filter is added and store it in the wraprec rather than doing it at runtime (which is slow, even with memoization in `wordpress_file_metadata` hashmap).

refactor: reduce # of wp plugin/theme name calculation

---

CONTRIBUTING.md
README.md
STYLEGUIDE.md
agent/README.txt
agent/newrelic-install.sh
agent/scripts/newrelic.ini.template
axiom/tests/cross_agent_tests/sql_obfuscation/README.md

Change user-facing documentation links to use `https` instead of `http`

chore(docs): use https for docs links

---

agent/fw_wordpress.c
agent/php_newrelic.h
agent/php_nrini.c
agent/scripts/newrelic.ini.template
tests/integration/frameworks/wordpress/test_wordpress_00.php
tests/integration/frameworks/wordpress/test_wordpress_00.php7.php
tests/integration/frameworks/wordpress/test_wordpress_00_1.php
tests/integration/frameworks/wordpress/test_wordpress_00_2.php
tests/integration/frameworks/wordpress/test_wordpress_02.php
tests/integration/frameworks/wordpress/test_wordpress_03.php
tests/integration/frameworks/wordpress/test_wordpress_03.php7.php
tests/integration/frameworks/wordpress/test_wordpress_04.php
tests/integration/frameworks/wordpress/test_wordpress_04.php7.php
tests/integration/frameworks/wordpress/test_wordpress_slow_hooks_only.php

Hide boolean flags controling wordpress hooks instrumentation behind
a `newrelic.framework.wordpress.hooks.options` facade. The facade makes
invalid combinations of boolean flags impossible to set. Additionally
do not surprise users with a change to agent behavior. Set the new toggles
to values that maintain behavior. This allows for transition period when
users can understand the new feature and be prepared for the change.

refactor: improve wordpress hooks ini

---

agent/fw_drupal.c
agent/lib_zend_http.c
agent/php_api_datastore.c
agent/php_execute.c
agent/php_stacked_segment.c
agent/php_stacked_segment.h
agent/php_txn.c
agent/tests/test_php_stacked_segment.c

Because OAPI doesn't create a nice callstack that replicates the PHP callstack, stacked segments make little/no sense in its context. Instead, we want to utilize the segment pool available in txn's.
force_current_segment was how stacked segments were able to maintain their context in a txn while not being on the segment stack. For OAPI, there is no reason to use this field, as the current segment will just be the top of the txn's segment stack.

feat(oapi): use segment pool instead of stacked segments

---

src/newrelic/integration/parse.go
src/newrelic/integration/test.go

This change determines if the string "null" (with leading and trailing whitespace) was given as the `EXPECT_PHP_PACKAGES` stanza body and if so sets it to "null" to simplify later processing.
Changes needed to test PR #818.

tests: simplify EXPECTED_PHP_PACKAGES "null" value processing

---

src/newrelic/integration/php_packages.go
src/newrelic/integration/test.go

This PR includes the following:
- Removes the "options" option which was used to specify that detected packages would not have version info.  This was applied to all packages detected and was too limiting as some test cases had some packages with versions and others without (laravel for example).  This has been replaced with the "package_names_only" options which allows giving a comma separated list of packages which only have names detected.
- Adds checks to verify only one of "supported_packages" or "expected_packages" is given.
- Improves how "expected_packages" was implemented to overcome some internal issues that existed.

tests: improve EXPECT_PHP_PACKAGES processing

---

src/newrelic/integration/php_packages.go
src/newrelic/integration/string_slice.go
src/newrelic/integration/test.go

To retain ability to build on older golang compilers.

fix(tests): Reverts use of slices.Contains

---

agent/fw_drupal8.c
agent/fw_hooks.h
agent/fw_wordpress.c
agent/lib_phpunit.c
agent/php_execute.c

This amendment does the following:
- Modified how Drupal extracts the version in a more robust way.
- Ensure Wordpress extracts the version without erroring out
- Remove Phpunit version extraction code

Release 10.17 Amendment

---

src/integration_runner/main.go
tests/integration/opcache/disabled/opcache_test.inc
tests/integration/opcache/disabled/skipif.inc
tests/integration/opcache/disabled/test_computations.php
tests/integration/opcache/disabled/test_even_odd_count.php
tests/integration/opcache/disabled/test_recursion_no_segfault.php
tests/integration/opcache/disabled/test_span_class_function.php
tests/integration/opcache/disabled/test_span_events_are_created_from_segments.php
tests/integration/opcache/disabled/test_span_events_are_created_upon_caught_error.php
tests/integration/opcache/disabled/test_span_events_are_created_upon_exit.php
tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_error.php
tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_handled_exception.php
tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_handled_exception.php7.php
tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_handled_exception_invalid_handler.php
tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_unhandled_exception.php
tests/integration/opcache/disabled/test_span_events_error_collector_disabled.php
tests/integration/opcache/disabled/test_span_events_exception_caught_nested.php
tests/integration/opcache/disabled/test_span_events_exception_caught_nested_rethrown.php
tests/integration/opcache/disabled/test_span_events_exception_caught_notice_error.php
tests/integration/opcache/disabled/test_span_events_exception_caught_notice_error_nested.php
tests/integration/opcache/disabled/test_span_events_exception_caught_same_span.php
tests/integration/opcache/disabled/test_span_events_exception_uncaught_nested.php
tests/integration/opcache/disabled/test_span_events_exist_when_no_segments.php
tests/integration/opcache/disabled/test_span_events_hsm_error.php
tests/integration/opcache/disabled/test_span_events_notice_error.php
tests/integration/opcache/disabled/test_span_events_on_dt_off_cat_off.php
tests/integration/opcache/disabled/test_span_events_on_dt_off_cat_on.php
tests/integration/opcache/disabled/test_span_events_root_parent.php
tests/integration/opcache/enabled/test_opcache.php

* Enable the opcache.so extension by default in the integration_runner
* Ensure the opcache INI settings in the integration_runner environment are enabled (these can be overwritten in the test case INI section if needing to test without opcache)
* Added few tests to ensure compatibility with opcache disabled and to demonstrate how to overwrite the value.

feat(tests): Enable opcache by default for the integration runner.

---

.github/workflows/code-coverage-baseline.yml
.github/workflows/make-agent.yml
.github/workflows/make-for-platform-on-arch.yml
.github/workflows/make-integration-tests.yml
.github/workflows/release-build.yml
.github/workflows/repolinter.yml
.github/workflows/test-agent.yml

Ensure that workflows use the versions of actions that are running on Node 20. Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), and GitHub [announced](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) its deprecation in GitHub Actions.
Actions upgraded:
- actions/checkout@v3 -> v4: https://github.com/actions/checkout/releases/tag/v4.0.0
* CHANGELOG: https://github.com/actions/checkout/blob/main/CHANGELOG.md
- docker/login-action@v2 -> v3: https://github.com/docker/login-action/releases/tag/v3.0.0
- docker/setup-qemu-action@v2 -> v3: https://github.com/docker/setup-qemu-action/releases/tag/v3.0.0
- codecov/codecov-action@v3 -> v3.1.5: https://github.com/codecov/codecov-action/releases/tag/v3.1.5
- …

ci: update GitHub Actions to use Node 20

---

agent/php_execute.c

Remove 'bootstrap/app.php' from the list of signature files used to detect
Laravel - Laravel is detected with 'illuminate/foundation/application.php'
for all supported Laravel versions: 6, 7, 8, 9 and 10.
Using 'bootstrap/app.php' causes Laravel to be detected before Lumen can be
detected because 'bootstrap/app.php' is the second file loaded when Lumen
based app is handling the request.

fix(agent): fix Lumen detection

---

daemon/internal/newrelic/integration/php_packages.go
daemon/internal/newrelic/integration/test.go

Adds a "override_versions_file" option for EXPECT_PHP_PACKAGE that allows specifying overrides for given expected versions detected.  This is useful for when a package did not modify the internal data structure used to by the agent to detect its version, causing the package test to fail.
The override file should be in the same directory as the test_php_package.php test and is a JSON file implementing a simple dictionary like:
{
"4.13.0": "4.12.0"
}
In this case this specifies if the packge version "4.13.0" is detected then override this expectation with the version "4.12.0".  In this example the upstream package bumped up to 4.13.0 but did not change the internal version variable so the agent still detects it as 4.12.0.

feat(tests): Adds override for package version

---

agent/php_error.c
agent/php_minit.c
agent/php_observer.c

Remove unwanted error reporting by overwriting zend_error_cb instead of using OAPI.

fix(agent): revert to using `zend_error_cb` hook for error reporting

---

agent/php_nrini.c
agent/scripts/newrelic.ini.template
tests/integration/frameworks/wordpress/test_wordpress_00.php
tests/integration/frameworks/wordpress/test_wordpress_00.php7.php
tests/integration/frameworks/wordpress/test_wordpress_00_1.php
tests/integration/frameworks/wordpress/test_wordpress_00_2.php
tests/integration/frameworks/wordpress/test_wordpress_apply_filters.php
tests/integration/frameworks/wordpress/test_wordpress_do_action.php
tests/integration/frameworks/wordpress/test_wordpress_transaction_name_hooks_on.php

By default the agent will only instrument hook callbacks from plugins/themes and will not instrument hook callbacks from wordpress core.

feat(agent): update default for wp hooks options

---

agent/php_internal_instrument.c
agent/php_mysqli.c
agent/php_mysqli.h
tests/integration/mysqli/test_explain_reused_id_multiple_001.php
tests/integration/mysqli/test_explain_reused_id_multiple_002.php

In GH issue #875 it was reported a warning is generated when using prepared statements with `mysqli`.  The issue included excellent instructions on how to reproduce the issue.  This PR addresses the cause of the warning.  
To understand the cause of the warning requires understanding how the agent handles `mysqli::stmt` objects.  When a SQL statement is prepared via mysqli the agent will store the SQL string in a global hashmap called `mysqli_queries` *if* the SQL is considered explainable (determined via `nr_php_explain_mysql_query_is_explainable()`), otherwise it is just ignored.  Later when a slow SQL query is detected the SQL string is retrieved and used to explain the query.
An additional factor is when a `mysqli::stmt` object is released it goes into a free pool PHP keeps which …

fix(agent): Fixes warning from mysqli when explaining slow SQL queries (GH issue 875)

---

tests/integration/mysqli/test_explain_reused_id_multiple_001.php

A EXPECT_SLOW_SQLS specification was left out of one test from PR #881 .

fix(tests): Fixes mysqli test by adding missing slowsql

---

agent/lib_guzzle6.c
daemon/cmd/integration_runner/main.go
daemon/internal/newrelic/integration/test.go
daemon/internal/newrelic/integration/test_test.go
tests/integration/external/guzzle6/test_bad_response_exception_async.php
tests/integration/external/guzzle6/test_bad_response_exception_sync.php
tests/integration/external/guzzle6/test_timeout_async.php
tests/integration/external/guzzle6/test_timeout_sync.php
tests/integration/external/guzzle6/test_transfer_exception_async.php
tests/integration/external/guzzle6/test_transfer_exception_sync.php
tests/integration/external/guzzle6/test_uncaught_bad_response_exception_sync.php
tests/integration/external/guzzle6/test_uncaught_transfer_exception_async.php
tests/integration/external/guzzle7/test_bad_response_exception_async.php
tests/integration/external/guzzle7/test_bad_response_exception_sync.php
tests/integration/external/guzzle7/test_timeout_async.php
tests/integration/external/guzzle7/test_timeout_sync.php
tests/integration/external/guzzle7/test_transfer_exception_async.php
tests/integration/external/guzzle7/test_transfer_exception_sync.php
tests/integration/external/guzzle7/test_uncaught_bad_response_exception_sync.php
tests/integration/external/guzzle7/test_uncaught_transfer_exception_async.php

Modify the onRejected handler to end guzzle's external segment even when
there's no response. This allows to mark the span as an external span and
capture the uri and method of the request. Additionally when sync requests is
rejected, onRejected callback is not called via `PromiseInterface::then` and
needs to be called manually.
Fixes #320.

fix(agent): end guzzle's external segment for rejected request

---

daemon/internal/newrelic/integration/test.go

Enhance EXPECT_METRICS_{DONT_}_EXIST by pretty printing actual metrics on test failure.

chore(tests): pretty print actual metrics

---

daemon/internal/newrelic/integration/test.go

The PHP package test was not being correctly checked for the case where the package was specified as `package_name_only` and a version was actually created for the package.

fix(tests): Fixes package-name-only test case

---

agent/lib_guzzle6.c

Guzzle 7+ was sending only the major version to the vm package If only major version is available, it should not be sent.
However, we can still use major version for the supportability metric.

fix(agent): Don't send only major version to vm package

---

agent/newrelic-install.sh

Some OSs stripped down to bare bones (like base OS container images) don't have all directories needed by the installer (e.g. /etc/init.d). Package installers simply create these directories. Make tarball installer behave similar to package installer and create required directories.
Fixes #905.

fix: install correctly on bare bones OSs

---

agent/newrelic-install.sh

Have the newrelic-install script log warning when it detects deprecated PHPs.

feat: deprecate PHPs 7.0 and 7.1

---

agent/php_execute.c

Addresses changes in Doctrine 2.18+ (but not 3.x) that affected detection.
There was a [commit](https://github.com/doctrine/orm/commit/073f2aa891249e582e63320cab34b035b591cf22) for Doctrine 2.18 that reworked the directory structure of the Doctrine library.  This PR adds another file for Doctrine to allow it to be auto-detected.

fix(agent): Fixes Doctrine 2.18+ detection

---

agent/fw_slim.c

1) the scheme for route run to correlate with proper OAPI naming was incorrectly listed and therefore txn naming precedence was incorrectly handled
2) this PR kept same naming scheme in route:run putting it before wrapper_call and saying ok to overwrite (instead of after and not ok to overwrite)
3) number 2 needed to incorporate fallback naming scheme 
4) added fallback naming scheme (since some errors and middleware intervention give the wrong txn name) using dispatcher:dispatch.
When there is an exception thrown in a route that is handled by the slim routing and error middleware, it is superseded by: Uncaught exception 'Slim\\Exception\\HttpNotFoundException' with message 'Not found.' and transformed into an http 404 error and is shown in the http.statuscode field as 404.  If the …

fix(agent): Slim txn naming updates

---

agent/scripts/init.alpine
agent/scripts/init.rhel

Systemd systems may not have access to the functions file provided by initscripts. The code from initscripts is provided under the GNU v2 license and will not be pulled in.
Additionally, a header comment block must be added, using https://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/initscrcomconv.html for specs

fix(scripts): fix rhel and alpine init scripts

---

daemon/cmd/daemon/main.go
daemon/cmd/stressor/main.go
daemon/internal/flatbuffersdata/data_test.go
daemon/internal/newrelic/collector/client.go
daemon/internal/newrelic/config/config.go
daemon/internal/newrelic/harvest_trigger.go
daemon/internal/newrelic/integration/parse.go
daemon/internal/newrelic/integration/php_packages.go
daemon/internal/newrelic/processor_test.go
daemon/internal/newrelic/utilization/utilization_hash.go

Apply `gofmt` suggestions preserving semantics of comments. go1.19 changed how `gofmt` formats [Go Doc Comments](https://go.dev/doc/comment) therefore some doc strings needed small adjustments from what `gofmt` suggested.

style(daemon): gofmt daemon module

---

daemon/internal/newrelic/integration/test.go

The logic for handling "__FILE__" was reversed and this PR fixes it.  The idea is that the actual JSON harvest will have the file name replaced with "__FILE__" and so the expected string should contain "__FILE__" and not have the actual file name inserted as the old code did.

fix(testing): Handles __FILE__ correctly for EXPECT_METRICS_EXIST

---

daemon/internal/newrelic/integration/test.go

The current code for EXPECT_METRICS_EXIST would verify the count of any metric was >0 before passing the test.  However, with apdex metrics the first field is not the count of metrics but the count of the number of times the transaction time was less than apdex_t.  This change allows for the count to be 0 for apdex metrics.

fix(testing): Fixes count check for apdex metrics

---

agent/lib_aws_sdk_php.c
axiom/nr_distributed_trace.c

Switches to use nr_strlcpy and nr_strcpy instead of libc versions for better platform generality.

chore(agent): Changes code to use NR string routines

---

daemon/internal/newrelic/integration/test.go

The existing code did not handle an Apdex metric correctly if a count of "1" was specified.  It only worked if no count was specified.  This change allows either form to work.

fix(testing): Handles Apdex metrics count correctly

---

.github/workflows/test-agent.yml

[`actions/upload-artifacts@v4.4.0`](https://github.com/actions/upload-artifact/releases/tag/v4.4.0) includes a breaking change of that causes hidden directories and files not being uploaded. Since code coverage artifacts are in `agent/.libs` directory, this functionality needs to disabled. Set `include-hidden-files` to true when uploading code coverage artifacts.

ci: fix test-pull-request workflow

---

agent/php_api.c
tests/integration/api/notice_error/test_bad_inputs.php
tests/integration/api/notice_error/test_good_1_arg_exception.php
tests/integration/api/notice_error/test_good_1_arg_exception_handler.php
tests/integration/api/notice_error/test_good_1_arg_string.php
tests/integration/api/notice_error/test_good_2_args.php
tests/integration/api/notice_error/test_good_4_args.php
tests/integration/api/notice_error/test_good_4_args_error_handler.php
tests/integration/api/notice_error/test_good_5_args.php
tests/integration/api/notice_error/test_good_5_args_error_handler.php

Starting with PHP 8.0 the `set_error_handler()` callback function signature drops the `$errcontext` final parameter so it only contains 4 parameters.  This caused using `newrelic_notice_error()` as a callback handler for PHP 8+ to not work as the API call did not accept only 4 arguments.  This PR adds support for this function signature.  There are also numerous tests added that will hopefully caught this kind of issue in the future.

fix(agent): Fixes newrelic_notice_error() API for PHP 8+

---

agent/newrelic-install.sh

Debian uses a directory called "mods-available" to house ini files. It's `phpenmod` and `phpdismod` allow command-line management of extensions in directory. It also creates a symlink ini file to this "mods-available" directory in the normal conf.d directory. The issue is that this symlink is prefixed with a number (for example 20-newrelic.ini). This prefix prevents our tarball installer from recognizing that a newrelic.ini already exists, resulting in 2 ini files: a newrelic.ini and a 20-newrelic.ini.
Our .deb package installer scouts out the "mods-available" directory and installs therein when possible. That means that if a customer installs via package but upgrades via tarball (not recommended), then their system gets the duplicates.
This change makes our tarball installer scout for a …

fix(installer): tarball installer checks for ini in mods-available

---

Makefile
docker-compose.yaml
docs/dev_environment.md
files/Dockerfile
files/set_path.sh

1. Add an option to control which PHP version is to be used in devenv service
via PHP env var passed at the time when dev-shell is started (or any dev-*
target is build).
2. Simplify `composer` and `go` install.
3. Fix `devenv` service image build for PHPs 7.2 and 7.3.
4. Apply `Dockerfile` best practices

chore: enhance dockerized development environment 

---

agent/fw_cakephp.c
agent/fw_hooks.h
agent/php_execute.c

This PR does the following:
- Modifies how the action name is retrieved, so that it is compatible with CakePHP 4.x and 5.x
- Adds correct detection file for CakePHP 4.x and 5.x
- Adds call to `nr_txn_suggest_package_supportability_metric` in `nr_cakephp_enable`

feat(agent): add support for CakePHP 4.x and 5.x

---

agent/config.m4
agent/tests/test_agent.c

PHP's build system received a fix for 'out of tree' builds - see https://github.com/php/php-src/pull/13516. This broke build of agent's unit tests which require agent's source directory to be in the include search path. Working agent's unit tests showed that `test_function_debug_name` needed its expectations tweaked - closures are named differently on PHP 8.4.

fix agent unit tests

---

agent/config.m4
agent/newrelic-install.sh
agent/php_includes.h
agent/tests/test_agent.c
make/release.mk

`ZEND_MODULE_API_NO` for PHP 8.4 is actually `20240924` - see https://github.com/php/php-src/blob/PHP-8.4/Zend/zend_modules.h#L34.

fix ZEND_8_4_X_API_NO value

---

docker-compose.yaml
files/Dockerfile

Fix QOL aliases and allow multiple devenvs to run simultanously.

chore: devenv enhancements

---

agent/lib_aws_sdk_php.c

Concerns about future/past proofing to the checking prioritized the non-eval implementation vs using the eval method for checking the version. However, aws-sdk-php internal functions frequently change without notice in the release notes. An extra eval is used to avoid the fatal error that would occur in the VERY unlikely event of Aws/Sdk.php not being found and which addresses the previous concerns while decoupling versioning from internal functions.

fix(agent): address the aws-sdk-php versioning change

---

.github/workflows/codeql.yml

Fix agent build scan by pinning runner to ubuntu-22.04. ubuntu-24.04, which is what ubuntu-latest has recently become, doesn't have agent's build dependency (libpcre3-dev) installed.

ci: fix CodeQL's agent scan (#1002)

---

.github/workflows/security-scan.yml

[`codeql-action/upload-sarif`](https://github.com/github/codeql-action/blob/v3/upload-sarif/action.yml#L12C3-L12C16) needs to know where the scanned code was checked out if it has been checked out to a subdir of `github.workspace`.

ci: fix scheduled security scan

---

.github/workflows/test-agent.yml
daemon/cmd/daemon/worker.go
daemon/internal/newrelic/utilization/kubernetes.go

Address issues spotted by `go vet`:
- [fix syntax of kubernetes.KubernetesServiceHost struct tags](https://github.com/newrelic/newrelic-php-agent/commit/d7ba91983f9b81a35afc05d2aa04dd38b99c8368)
- [ensure context.cancel() is always called to avoid context leak](https://github.com/newrelic/newrelic-php-agent/commit/c3e1e40465378e529315c21295159ade416e8894)
[Add go vet check for pull requests](https://github.com/newrelic/newrelic-php-agent/commit/630dcbffd5062fcfd1ebfe107ec6ab5b9b356161)

fix(daemon): enable `go vet` check on pull requests

---

agent/lib_aws_sdk_php.c

Instead of a blanket segment_start in the "before" function that needs to be discarded in the majority of the cases, just create the segment when it is needed, add the attributes/metrics, then close the segment.
DONE:Multiverse SQS exception tests need to be updated.
DONE:Needs additional testing against backend.

refactor(agent): reduce number of segments created

---

agent/fw_laravel_queue.c

Free strings that were strdup-ed but not being freed.

fix(agent): fix memleak in Laravel Queue instrumentation

---

axiom/nr_header.c
axiom/tests/test_header.c

This function created a new hashmap, but didn's pass the string dtor in so any strdupped values were not being freed when the hashmap was destroyed.
valgrind output from a multiverse run showed:
==220==    by 0x6AA4680: nr_strdup (util_memory.c:156)
==220==    by 0x6A83BD3: nr_header_create_distributed_trace_map (nr_header.c:60)
==220==    by 0x6A45D28: nr_php_amqplib_retrieve_dt_headers (lib_php_amqplib.c:503)
==220==    by 0x6A45D28: nr_rabbitmq_basic_get (lib_php_amqplib.c:742)
==220==    by 0x6A74993: nr_zend_call_orig_execute_special (php_user_instrument.c:105)
==220==    by 0x6A52EAA: nr_php_instrument_func_end (php_execute.c:2086)
==220==    by 0x6A54D5B: nr_php_observer_fcall_end (php_execute.c:2188)
==220==    by 0x71D7ED: zend_observer_fcall_end (in /usr/local/bin/php)
==220== …

fix(agent): Fix nr_header_create_distributed_trace_map mem leak when hashmap is destroyed

---

axiom/Makefile

Make the `HAVE_PROTOBUF_C != 0` check part of recipe where its needed rather than making the check in a phony target. Using phony target results in axiom rebuilding axiom every time.
Fixup of #1012.

build: fix axiom's build dependency check

---

agent/lib_aws_sdk_php.c
agent/lib_aws_sdk_php.h
agent/php_minit.c
agent/php_mshutdown.c
agent/php_newrelic.h
agent/php_nrini.c
agent/scripts/newrelic.ini.template
agent/tests/test_lib_aws_sdk_php.c
axiom/nr_segment.h
axiom/nr_segment_traces.c
axiom/nr_span_event.h

Instrument AWS Lambda `invoke` and reconstruct the ARN to facilitate a complete service map.

feat(agent): Add AWS Lambda Relationship

---

daemon/internal/newrelic/log_events.go
daemon/internal/newrelic/log_events_test.go

This PR corrects how the collector JSON for log forwarded labels handles log label key and values which have characters which must be escaped for JSON marshaling. The change is restricted to the daemon code to generate the log label JSON and does not impact the agent side of things.
The fix is to use the Go `json` module to handle the creation of the JSON.  It will handle the escaping as needed.  The array of label key/value pairs is converted to a Go `map` which is then marshaled into JSON.  The case where either the label or value is empty (an invalid label) is handled so that these are not forwarded.  This case should not occur as labels of this type should not be created by the agent but this check is added as additional protection against this case.

fix(daemon): Adds escaping for log forwarded labels

---

agent/fw_drupal8.c
tests/integration/frameworks/drupal/mock_module_handler_empty_array.php
tests/integration/frameworks/drupal/mock_module_handler_empty_key.php
tests/integration/frameworks/drupal/mock_module_handler_invalid_key.php
tests/integration/frameworks/drupal/mock_module_handler_invalid_map.php
tests/integration/frameworks/drupal/mock_module_handler_invalid_module.php
tests/integration/frameworks/drupal/mock_module_handler_invalid_value.php
tests/integration/frameworks/drupal/mock_module_handler_valid.php
tests/integration/frameworks/drupal/test_hook_implementations_map_empty_array.php
tests/integration/frameworks/drupal/test_hook_implementations_map_empty_key.php
tests/integration/frameworks/drupal/test_hook_implementations_map_invalid_key.php
tests/integration/frameworks/drupal/test_hook_implementations_map_invalid_map.php
tests/integration/frameworks/drupal/test_hook_implementations_map_invalid_module.php
tests/integration/frameworks/drupal/test_hook_implementations_map_invalid_value.php
tests/integration/frameworks/drupal/test_hook_implementations_map_valid.php

Adds support for Drupal Attribute Hooks added in Drupal 11.1.

feat(agent): Drupal hook attribute instrumentation

---

agent/php_user_instrument.c
agent/php_user_instrument_wraprec_hashmap.c

Make log messages easier to understand when adding a named custom tracer by logging only a single message. Instead of logging one message when the wraprec is added, and two messages when wraprec is re-used, log a single message that indicates if the wraprec was added or re-used.

refactor(agent): improve logging when adding named tracers

---

agent/lib_composer.c
agent/php_execute.c
agent/php_globals.h
agent/php_minit.c
agent/php_nrini.c
agent/scripts/newrelic.ini.template
tests/integration/autoloader/test_autoloader_with_composer_disabled.php
tests/integration/autoloader/test_autoloader_without_composer_disabled.php
tests/integration/external/guzzle5/test_cat.php
tests/integration/external/guzzle5/test_dt.php
tests/integration/external/guzzle5/test_dt_newrelic_header_disabled.php
tests/integration/external/guzzle5/test_dt_synthetics.php
tests/integration/external/guzzle5/test_dt_synthetics_logging_off.php
tests/integration/external/guzzle5/test_no_cat_no_dt.php
tests/integration/external/guzzle6/test_cat.php
tests/integration/external/guzzle6/test_dt.php
tests/integration/external/guzzle6/test_dt_newrelic_header_disabled.php
tests/integration/external/guzzle6/test_dt_synthetics.php
tests/integration/external/guzzle6/test_dt_synthetics_logging_off.php
tests/integration/external/guzzle6/test_no_cat_no_dt.php
tests/integration/external/guzzle7/test_cat.php
tests/integration/external/guzzle7/test_dt.php
tests/integration/external/guzzle7/test_dt_newrelic_header_disabled.php
tests/integration/external/guzzle7/test_dt_synthetics.php
tests/integration/external/guzzle7/test_no_cat_no_dt.php

Changes the default configuration value for composer-based package detection to `true`.
An additional configuration value, `newrelic.vulnerability_management.composer_api.per_process_detection`, has also been added to control the frequency at which composer sampling occurs. By default, this setting will be enabled, only sampling Composer API data once per php-fpm process. This improves baseline performance to make the enablement of Composer API package detection a negligible overhead impact.

feat(agent): composer api package detection on by default

---

agent/php_curl.c

This PR removes obsolete `PHP7` codeblocks. PR: 5/17

chore(agent): remove obsolete code (5/17)

---

agent/php_pdo_private.h

This PR removes obsolete `PHP7` codeblocks. PR: 11/17

chore(agent): remove obsolete code (11/17)

---

agent/php_wrapper.c

This PR removes obsolete `PHP7` codeblocks. PR: 14/17

chore(agent): remove obsolete code (14/17)

---

agent/fw_drupal8.c
agent/fw_laravel.c
agent/fw_lumen.c
agent/lib_guzzle4.c
agent/lib_guzzle6.c
agent/php_agent.c
agent/php_agent.h
agent/php_api.c
agent/php_call.c
agent/php_environment.c
agent/php_execute.c
agent/php_includes.h
agent/php_internal_instrument.c
agent/php_output.c
agent/php_stack.c
agent/php_txn.c
agent/tests/test_mongodb.c
agent/tests/test_output.c
agent/tests/tlib_php.c

This PR removes obsolete PHP 5.x `ZEND_MODULE_API_NO` usage from the agent codebase.

chore(agent): remove obsolete PHP 5.x ZEND_MODULE_API_NO usage

---

agent/lib_composer.c
agent/php_execute.c
agent/php_globals.h
agent/php_minit.c
agent/php_txn.c
axiom/nr_txn.c
axiom/nr_txn.h
axiom/tests/test_txn.c

When Composer runtime API is used to get packages information, the
agent should not generate packages information using legacy methods.
This solves the problem of package data detected with the help of
Composer's runtime API not to be sent to the backend in environments
using “once-per-process” setting. The reason for is that the first 
request generates package information using Composer's runtime API
but every next request only generates package information using legacy
method. This in conjunction with the fact that daemon is only sending
the last package information received from the daemon leads to a
situation that package information returned by Composer runtime API
is lost and never makes it to the backend.

fix(agent): fix legacy package detection issues

---

Makefile

Set `GOTOOLCHAIN` to `auto` to ensure go toolchain from `daemon/go.mod` will always be used.

chore(build): force golang toolchain from daemon/go.mod
