newrelic/newrelic-php-agent

- .github/workflows/release-build.yml
Release build workflow which must be manually triggered as it does not trigger on push/pull.
> PHP:  Release Build workflow

- agent/php_vm.c
* The assumption that the new `ZEND_CHECK_UNDEF_ARGS` would always exist and therefore we needed to index back two spaces was incorrect.  We need to account for it existing and not existing.
* `pr_build.sh` does not enable valgrind yet.  This will be enabled again in the 32bit PR.
> PHP 8.0 and valgrind mem issue on 64bit architecture.

- docs/development.md
The development guide should show that we support PHP 8.
> Update dev guide for php 8

- agent/php_internal_instrument.c
* Fixes `mysqli_commit` instrumentation returning NULL.
* Utilizes already existing function to more cleanly handle the datastore segment.
> Fixes `mysqli_commit` instrumentation returning NULL in some cases.

- Makefile
- docs/development.md
This updates the dev guide and the makefile to account for the correct PHP versions
> Update documentation and Makefile to the correct PHP versions

- CONTRIBUTING.md
Our practice is to add new PRs to `dev`.
> Update CONTRIBUTING.md to indicate to contributors to add PRs to `dev`.

- Makefile
- docs/development.md
- make/release.mk
Added support for PHP 8.1 release to `Makefile` and `make\release`.
Modified documentation.
> Release build updates

- tests/integration/errors/test_large_error_message.php
This test is added to verify that our agent does not have a error message max size
Closes #362
> test(integration): Add test for large error inbox

- src/newrelic/collector/collector_test.go
This adds a required test case for #437 by verifying that the request_headers_map headers are properly added to a collector request.
The actual change is very simple but since this file was not correctly formatted by gofmt I also corrected that.  Viewing the PR with whitespace changes ignored will show the actual changes.
> test(daemon): Test request_headers_map for collector requests

- src/newrelic/collector/client.go
- src/newrelic/processor.go
https://github.com/newrelic/newrelic-php-agent/issues/441
> feat(logs): P17 log response codes

- axiom/tests/cross_agent_tests/distributed_tracing/distributed_tracing.json
- axiom/tests/cross_agent_tests/distributed_tracing/trace_context.json
- axiom/tests/cross_agent_tests/sql_obfuscation/sql_obfuscation.json
- axiom/tests/cross_agent_tests/utilization_vendor_specific/aws.json
- axiom/tests/test_txn.c
- axiom/util_object.c
- axiom/util_object.h
- src/newrelic/utilization/aws.go
Integrate the latest Cross Agent Tests to align with other agents.
Changes to 'exact' value representations of some outbound payloads required the addition of helper functions to convert 'found' values to strings in order to support comparisons.
A handful of issues were identified during this integration that require a more thorough examination, and their changes have been omitted from this PR:
- https://github.com/newrelic/newrelic-php-agent/issues/473
- https://github.com/newrelic/newrelic-php-agent/issues/474
Closes #448
> feat(tests): cross agent test integration

- agent/lib_monolog.c
This PR disables `$context` argument of `Monolog\Logger::addRecord` instrumentation. 
Context is no longer appended to the message in the log record. The code instrumenting
context can be re-enabled at compile time based on the  `HAVE_CONTEXT_IN_MESSAGE` 
macro value:
* 0 - `$context` argument will not be instrumented: its existence and value are ignored 
* 1 - the message of the log record forwarded by the agent will include the value of `$context`, which is appended to the value of `$message`.
> fix(agent): don't instrument Monolog's $context

- agent/lib_monolog.c
Removes an unwanted logging message from the agent.
> fix(agent): Remove unwanted log message

- axiom/nr_log_event.c
- axiom/tests/test_log_event.c
- tests/integration/logging/monolog2/test_monolog_escape_chars.php
- tests/integration/logging/monolog3/test_monolog_escape_chars.php
This PR improves the conversion of log message strings to JSON for transmission to the collector.
> fix(agent): Improve message conversion to JSON

- axiom/nr_segment_datastore.c
Datastore segments are not allowed to have children segments since it would scramble the exclusive time calculation.
It is enforced here where we use the API to create a datastore segment: https://github.com/newrelic/newrelic-php-agent/blob/main/agent/php_api_datastore.c#L195
However, it was not enforced when we automatically create a datastore segment.
There is already a test case that verifies it here: https://github.com/newrelic/newrelic-php-agent/blob/main/tests/integration/api/datastore/test_all_parameters_no_children.php
During CLM debugging, this case would fail, but after the fix it succeeds.
> fix(agent): Datastore segments should not have children segments.

- tests/integration/lang/test_generator_7.1-7.4.php
- tests/integration/lang/test_generator_8.0.php
* Update 7.1 test_generator for PHP version range 7.1 - 7.4
* Add new test for PHP version 8.0+
> tests(integration): update generator tests for oapi

- tests/integration/mysqli/test_explain_connect.php
- tests/integration/mysqli/test_explain_construct.php
- tests/integration/mysqli/test_explain_database_no_user.php
- tests/integration/mysqli/test_explain_init_oo.php
- tests/integration/mysqli/test_explain_init_oo_persistent.php
- tests/integration/mysqli/test_explain_init_proc.php
- tests/integration/mysqli/test_explain_leading_whitespace.php
- tests/integration/mysqli/test_explain_options_garbage.php
- tests/integration/mysqli/test_explain_real_connect_garbage.php
- tests/integration/mysqli/test_explain_reused_id.php
- tests/integration/mysqli/test_explain_select_db_oo.php
- tests/integration/mysqli/test_explain_select_db_proc.php
- tests/integration/mysqli/test_prepare_oo.php
- tests/integration/mysqli/test_prepare_proc.php
- tests/integration/mysqli/test_query_oo.php
- tests/integration/mysqli/test_query_proc.php
- tests/integration/mysqli/test_real_query_proc.php
A few tests missed my automated script (differently formatted metrics section) so these were the stragglers.
> tests(agent): Update mysqli tests to follow logging default

- tests/integration/attributes/test_transaction_closure_clm_off.php
- tests/integration/attributes/test_transaction_namespace2_clm_off.php
- tests/integration/attributes/test_transaction_namespace_clm_off.php
- tests/integration/attributes/test_transaction_namespace_len_clm_off.php
- tests/integration/attributes/test_transaction_nested_user_functions_clm_off.php
- tests/integration/attributes/test_transaction_non_web_clm_off.php
- tests/integration/attributes/test_transaction_web_clm_off.php
- tests/integration/logging/monolog3/test_monolog_basic_clm_off.php
Add sanity tests to verify agent functionality when CLM is explicitly disabled.
> feat(tests): add tests exercising CLM 'off' functionality

- .github/workflows/release-build.yml
- make/release.mk
Update release-build workflow to build daemon using recent version of golang.
> ci: build daemon with release build workflow

- agent/newrelic-install.sh
Don't check if zts binaries are in agent's install bundle. 
Abort installation on system with PHP with ZTS.
> chore(install): Disable ZTS

- agent/newrelic-install.sh
First round of changes to support installing an agent on aarch64 systems.
> feat: add support for installing on aarch64 systems

- agent/fw_drupal8.c
- agent/newrelic-install.sh
- agent/php_wrapper.c
- agent/php_wrapper.h
- tests/integration/frameworks/drupal/mock_module_handler.php
- tests/integration/frameworks/drupal/test_invoke_all_with.php
https://github.com/newrelic/newrelic-php-agent/pull/670 updated version merged to main
> Release 10.11

- .gitignore
- files/Dockerfile
Add a number of enhancements/fixes to the current development environment setup
- add .vscode to .gitignore
- remove broken mysqli install
- programmatically determine PHP version for uopz/memcache docker install for compatibility with PHP < 8.0
- remove dead reference to mongo extension installations
- add QOL aliases to the container to make a clean rebuild and integration tests easier to run
> chore: development environment enhancements

- src/daemon/main.go
- src/daemon/worker.go
- src/newrelic/collector/client.go
- src/newrelic/collector/collector_test.go
- src/newrelic/processor.go
Follows the ideas set out in https://github.com/newrelic/go-agent/pull/828/files
> feat(daemon): improve logging obfuscation

- agent/php_call.c
zend_try/zend_catch is to handle Zend Exceptions not PHP exceptions - see [here](https://github.com/newrelic/newrelic-php-agent/blob/320ea571a11bc469d7d8179dfe51577b54df11df/agent/php_user_instrument.c#L17-L50) for more details. They were added in this [commit](https://github.com/newrelic/newrelic-php-agent/pull/580/commits/66eccf7d58d979737b7859308a95cddeb4f08f2e) to handle misbehaving PHP embed SAPI that threw Zend Exception when PHP code that was called via nr_php_call threw PHP Exception. PHP CLI or CGI SAPIs don’t throw Zend Exception when PHP code that was called threw PHP Exception and therefore zend_try/zend_catch is effectively a dead code.
> fix(agent): revert zend_try/catch php call logic

- src/newrelic/integration/test.go
Adds support for using "__FILE__" in the metrics which are checked.
> feat(testing): Extends EXPECT_METRICS_EXIST, EXPECT_METRICS_DONT_EXIST 

- .github/workflows/test-agent.yml
Add gofmt check to test-agent workflow which will check pull request for daemon's code formatting deviations from go code formatting standards.
> ci: add gofmt check to test-agent workflow

- .github/workflows/trigger-test-suite.yml
Corrects the name and description for trigger-test-suite to reflect the test suite workflow rather than just multiverse.
> fix(ci): correct trigger-test-suite name and description

- .github/workflows/issue-comment.yml
Fix gh command failure when no github repository can be found.
> ci: fix issue response

- agent/fw_codeigniter.c
This PR removes obsolete `PHP7` codeblocks. PR: 1/17
> chore(agent): remove obsolete code (1/17)

- agent/php_api.c
This PR removes obsolete `PHP7` codeblocks. PR: 3/17
> chore(agent): remove obsolete code (3/17) 

- agent/php_hash.c
This PR removes obsolete `PHP7` codeblocks. PR: 8/17
> chore(agent): remove obsolete code (8/17)

- agent/php_hash.h
This PR removes obsolete `PHP7` codeblocks. PR: 9/17
> chore(agent): remove obsolete code (9/17)

- agent/php_nrini.c
This PR removes obsolete `PHP7` codeblocks. PR: 10/17
> chore(agent): remove obsolete code (10/17)

- agent/php_zval.h
This PR removes obsolete `PHP7` codeblocks. PR: 15/17
> chore(agent): remove obsolete code (15/17)

- agent/tests/test_call.c
- agent/tests/test_fw_codeigniter.c
- agent/tests/test_pdo.c
- agent/tests/tlib_php.c
This PR removes obsolete `PHP7` codeblocks. PR: 16/17
> chore(agent): remove obsolete code (16/17)
